/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ClaimAppealModel } from '../../models/claim-appeal-model';

export interface ClaimAppealGetInvoiceAppealById$Params {

/**
 * Invoice Appeal ID
 */
  id: string;
}

export function claimAppealGetInvoiceAppealById(http: HttpClient, rootUrl: string, params: ClaimAppealGetInvoiceAppealById$Params, context?: HttpContext): Observable<StrictHttpResponse<ClaimAppealModel>> {
  const rb = new RequestBuilder(rootUrl, claimAppealGetInvoiceAppealById.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ClaimAppealModel>;
    })
  );
}

claimAppealGetInvoiceAppealById.PATH = '/api/claimappeals/{id}/invoiceAppeal';
