/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FileUploadProjectAppeal } from '../../models/file-upload-project-appeal';

export interface AttachmentGetProjectAppealAttachments$Params {

/**
 * The project appeal Id.
 */
  projectAppealId?: string;
}

export function attachmentGetProjectAppealAttachments(http: HttpClient, rootUrl: string, params?: AttachmentGetProjectAppealAttachments$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FileUploadProjectAppeal>>> {
  const rb = new RequestBuilder(rootUrl, attachmentGetProjectAppealAttachments.PATH, 'get');
  if (params) {
    rb.query('projectAppealId', params.projectAppealId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<FileUploadProjectAppeal>>;
    })
  );
}

attachmentGetProjectAppealAttachments.PATH = '/api/attachments/byProjectAppealId';
