/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FileUpload } from '../../models/file-upload';

export interface AttachmentGetAmendmentAttachments$Params {

/**
 * The project Id.
 */
  projectId?: string;
}

export function attachmentGetAmendmentAttachments(http: HttpClient, rootUrl: string, params?: AttachmentGetAmendmentAttachments$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FileUpload>>> {
  const rb = new RequestBuilder(rootUrl, attachmentGetAmendmentAttachments.PATH, 'get');
  if (params) {
    rb.query('projectId', params.projectId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<FileUpload>>;
    })
  );
}

attachmentGetAmendmentAttachments.PATH = '/api/attachments/byProjectId';
