/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FileUploadClaim } from '../../models/file-upload-claim';

export interface AttachmentUpsertDeleteClaimAttachment$Params {
  
    /**
     * The attachment information
     */
    body: FileUploadClaim
}

export function attachmentUpsertDeleteClaimAttachment(http: HttpClient, rootUrl: string, params: AttachmentUpsertDeleteClaimAttachment$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, attachmentUpsertDeleteClaimAttachment.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<string>;
    })
  );
}

attachmentUpsertDeleteClaimAttachment.PATH = '/api/attachments/claimdocument';
