/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FileUploadClaimAppeal } from '../../models/file-upload-claim-appeal';

export interface AttachmentUpsertDeleteClaimAppealAttachment$Params {
  
    /**
     * The attachment information
     */
    body: FileUploadClaimAppeal
}

export function attachmentUpsertDeleteClaimAppealAttachment(http: HttpClient, rootUrl: string, params: AttachmentUpsertDeleteClaimAppealAttachment$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, attachmentUpsertDeleteClaimAppealAttachment.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<string>;
    })
  );
}

attachmentUpsertDeleteClaimAppealAttachment.PATH = '/api/attachments/claimappealdocument';
