/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FileUploadClaimAppeal } from '../../models/file-upload-claim-appeal';

export interface AttachmentGetClaimAppealAttachments$Params {

/**
 * The appeal Id.
 */
  claimAppealId?: string;
}

export function attachmentGetClaimAppealAttachments(http: HttpClient, rootUrl: string, params?: AttachmentGetClaimAppealAttachments$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FileUploadClaimAppeal>>> {
  const rb = new RequestBuilder(rootUrl, attachmentGetClaimAppealAttachments.PATH, 'get');
  if (params) {
    rb.query('claimAppealId', params.claimAppealId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<FileUploadClaimAppeal>>;
    })
  );
}

attachmentGetClaimAppealAttachments.PATH = '/api/attachments/byClaimAppealId';
