/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CurrentInvoice } from '../../models/current-invoice';

export interface InvoiceGetDfaInvoices$Params {

/**
 * The claim Id.
 */
  claimId?: string;
}

export function invoiceGetDfaInvoices(http: HttpClient, rootUrl: string, params?: InvoiceGetDfaInvoices$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CurrentInvoice>>> {
  const rb = new RequestBuilder(rootUrl, invoiceGetDfaInvoices.PATH, 'get');
  if (params) {
    rb.query('claimId', params.claimId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<CurrentInvoice>>;
    })
  );
}

invoiceGetDfaInvoices.PATH = '/api/invoices/dfainvoices';
