version: 2
updates:
  # NuGet dependencies
  - package-ecosystem: "nuget"
    directory: "/dfa-public/src/API"
    target-branch: "develop"
    schedule:
      interval: "daily"
  # npm dependencies - frontend
  - package-ecosystem: "npm"
    directory: "/dfa-public/src/UI"
    target-branch: "develop"
    schedule:
      interval: "daily"
