sonar.projectName=dfa

# Path to sources
sonar.sources=dfa/src/API,dfa/src/UI,dfa-public/src/API,dfa-public/src/UI
#sonar.exclusions=
#sonar.inclusions=

# Path to tests
sonar.tests=
#sonar.test.exclusions=
#sonar.test.inclusions=

# Source encoding
sonar.sourceEncoding=UTF-8

# Exclusions for copy-paste detection
#sonar.cpd.exclusions=