/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface ContactCreateAuditEvent$Params {

/**
 * Brief description of event type; eg. "login", or "submit Application"
 */
  eventMoniker?: string;
}

export function contactCreateAuditEvent(http: HttpClient, rootUrl: string, params?: ContactCreateAuditEvent$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, contactCreateAuditEvent.PATH, 'get');
  if (params) {
    rb.query('eventMoniker', params.eventMoniker, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<string>;
    })
  );
}

contactCreateAuditEvent.PATH = '/api/contacts/createaudit';
