/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AmendmentFileMetadataUpload } from '../../models/amendment-file-metadata-upload';

export interface AmendmentAttachmentGetAttachmentsByAmendmentId$Params {

/**
 * The amendment Id.
 */
  amendmentId?: string;
}

export function amendmentAttachmentGetAttachmentsByAmendmentId(http: HttpClient, rootUrl: string, params?: AmendmentAttachmentGetAttachmentsByAmendmentId$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AmendmentFileMetadataUpload>>> {
  const rb = new RequestBuilder(rootUrl, amendmentAttachmentGetAttachmentsByAmendmentId.PATH, 'get');
  if (params) {
    rb.query('amendmentId', params.amendmentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<AmendmentFileMetadataUpload>>;
    })
  );
}

amendmentAttachmentGetAttachmentsByAmendmentId.PATH = '/api/amendment/attachments/byAmendmentId';
