/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AmendmentFileUpload } from '../../models/amendment-file-upload';

export interface AmendmentAttachmentUpsertAttachment$Params {
  
    /**
     * The attachment data.
     */
    body: AmendmentFileUpload
}

export function amendmentAttachmentUpsertAttachment(http: HttpClient, rootUrl: string, params: AmendmentAttachmentUpsertAttachment$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, amendmentAttachmentUpsertAttachment.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<string>;
    })
  );
}

amendmentAttachmentUpsertAttachment.PATH = '/api/amendment/attachments';
