/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { appealAttachmentDeleteAttachment } from '../fn/appeal-attachment/appeal-attachment-delete-attachment';
import { AppealAttachmentDeleteAttachment$Params } from '../fn/appeal-attachment/appeal-attachment-delete-attachment';
import { appealAttachmentGetAttachmentsByAppealId } from '../fn/appeal-attachment/appeal-attachment-get-attachments-by-appeal-id';
import { AppealAttachmentGetAttachmentsByAppealId$Params } from '../fn/appeal-attachment/appeal-attachment-get-attachments-by-appeal-id';
import { appealAttachmentGetAttachmentsByCaseId } from '../fn/appeal-attachment/appeal-attachment-get-attachments-by-case-id';
import { AppealAttachmentGetAttachmentsByCaseId$Params } from '../fn/appeal-attachment/appeal-attachment-get-attachments-by-case-id';
import { appealAttachmentUpsertAttachment } from '../fn/appeal-attachment/appeal-attachment-upsert-attachment';
import { AppealAttachmentUpsertAttachment$Params } from '../fn/appeal-attachment/appeal-attachment-upsert-attachment';
import { AppealFileMetadataUpload } from '../models/appeal-file-metadata-upload';

@Injectable({ providedIn: 'root' })
export class AppealAttachmentService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `appealAttachmentUpsertAttachment()` */
  static readonly AppealAttachmentUpsertAttachmentPath = '/api/appeal/attachments';

  /**
   * Create / update a file attachment.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `appealAttachmentUpsertAttachment()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  appealAttachmentUpsertAttachment$Response(params: AppealAttachmentUpsertAttachment$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return appealAttachmentUpsertAttachment(this.http, this.rootUrl, params, context);
  }

  /**
   * Create / update a file attachment.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `appealAttachmentUpsertAttachment$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  appealAttachmentUpsertAttachment(params: AppealAttachmentUpsertAttachment$Params, context?: HttpContext): Observable<string> {
    return this.appealAttachmentUpsertAttachment$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `appealAttachmentDeleteAttachment()` */
  static readonly AppealAttachmentDeleteAttachmentPath = '/api/appeal/attachments';

  /**
   * Delete a file attachment.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `appealAttachmentDeleteAttachment()` instead.
   *
   * This method doesn't expect any request body.
   */
  appealAttachmentDeleteAttachment$Response(params?: AppealAttachmentDeleteAttachment$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return appealAttachmentDeleteAttachment(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete a file attachment.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `appealAttachmentDeleteAttachment$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  appealAttachmentDeleteAttachment(params?: AppealAttachmentDeleteAttachment$Params, context?: HttpContext): Observable<string> {
    return this.appealAttachmentDeleteAttachment$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `appealAttachmentGetAttachmentsByAppealId()` */
  static readonly AppealAttachmentGetAttachmentsByAppealIdPath = '/api/appeal/attachments/byAppealId';

  /**
   * Get a collection of appeal attachments by appeal Id.
   * Note: This does not return the actual file data, only the dynamics attachment metadata records.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `appealAttachmentGetAttachmentsByAppealId()` instead.
   *
   * This method doesn't expect any request body.
   */
  appealAttachmentGetAttachmentsByAppealId$Response(params?: AppealAttachmentGetAttachmentsByAppealId$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AppealFileMetadataUpload>>> {
    return appealAttachmentGetAttachmentsByAppealId(this.http, this.rootUrl, params, context);
  }

  /**
   * Get a collection of appeal attachments by appeal Id.
   * Note: This does not return the actual file data, only the dynamics attachment metadata records.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `appealAttachmentGetAttachmentsByAppealId$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  appealAttachmentGetAttachmentsByAppealId(params?: AppealAttachmentGetAttachmentsByAppealId$Params, context?: HttpContext): Observable<Array<AppealFileMetadataUpload>> {
    return this.appealAttachmentGetAttachmentsByAppealId$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<AppealFileMetadataUpload>>): Array<AppealFileMetadataUpload> => r.body)
    );
  }

  /** Path part for operation `appealAttachmentGetAttachmentsByCaseId()` */
  static readonly AppealAttachmentGetAttachmentsByCaseIdPath = '/api/appeal/attachments/byCaseId';

  /**
   * Get a collection of appeal attachments by case Id.
   * Note: This does not return the actual file data, only the dynamics attachment metadata records.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `appealAttachmentGetAttachmentsByCaseId()` instead.
   *
   * This method doesn't expect any request body.
   */
  appealAttachmentGetAttachmentsByCaseId$Response(params?: AppealAttachmentGetAttachmentsByCaseId$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AppealFileMetadataUpload>>> {
    return appealAttachmentGetAttachmentsByCaseId(this.http, this.rootUrl, params, context);
  }

  /**
   * Get a collection of appeal attachments by case Id.
   * Note: This does not return the actual file data, only the dynamics attachment metadata records.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `appealAttachmentGetAttachmentsByCaseId$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  appealAttachmentGetAttachmentsByCaseId(params?: AppealAttachmentGetAttachmentsByCaseId$Params, context?: HttpContext): Observable<Array<AppealFileMetadataUpload>> {
    return this.appealAttachmentGetAttachmentsByCaseId$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<AppealFileMetadataUpload>>): Array<AppealFileMetadataUpload> => r.body)
    );
  }

}
