/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { DisasterEvent } from '../models/disaster-event';
import { EffectedRegionCommunity } from '../models/effected-region-community';
import { eligibilityGetEvents } from '../fn/eligibility/eligibility-get-events';
import { EligibilityGetEvents$Params } from '../fn/eligibility/eligibility-get-events';
import { eligibilityGetOpenEvents } from '../fn/eligibility/eligibility-get-open-events';
import { EligibilityGetOpenEvents$Params } from '../fn/eligibility/eligibility-get-open-events';
import { eligibilityGetRegionCommunties } from '../fn/eligibility/eligibility-get-region-communties';
import { EligibilityGetRegionCommunties$Params } from '../fn/eligibility/eligibility-get-region-communties';

@Injectable({ providedIn: 'root' })
export class EligibilityService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `eligibilityGetEvents()` */
  static readonly EligibilityGetEventsPath = '/api/eligibility/checkEventsAvailable';

  /**
   * Checking events are present in the system.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `eligibilityGetEvents()` instead.
   *
   * This method doesn't expect any request body.
   */
  eligibilityGetEvents$Response(params?: EligibilityGetEvents$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
    return eligibilityGetEvents(this.http, this.rootUrl, params, context);
  }

  /**
   * Checking events are present in the system.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `eligibilityGetEvents$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  eligibilityGetEvents(params?: EligibilityGetEvents$Params, context?: HttpContext): Observable<number> {
    return this.eligibilityGetEvents$Response(params, context).pipe(
      map((r: StrictHttpResponse<number>): number => r.body)
    );
  }

  /** Path part for operation `eligibilityGetOpenEvents()` */
  static readonly EligibilityGetOpenEventsPath = '/api/eligibility/openEvents';

  /**
   * Retrieve list of open events.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `eligibilityGetOpenEvents()` instead.
   *
   * This method doesn't expect any request body.
   */
  eligibilityGetOpenEvents$Response(params?: EligibilityGetOpenEvents$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DisasterEvent>>> {
    return eligibilityGetOpenEvents(this.http, this.rootUrl, params, context);
  }

  /**
   * Retrieve list of open events.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `eligibilityGetOpenEvents$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  eligibilityGetOpenEvents(params?: EligibilityGetOpenEvents$Params, context?: HttpContext): Observable<Array<DisasterEvent>> {
    return this.eligibilityGetOpenEvents$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<DisasterEvent>>): Array<DisasterEvent> => r.body)
    );
  }

  /** Path part for operation `eligibilityGetRegionCommunties()` */
  static readonly EligibilityGetRegionCommuntiesPath = '/api/eligibility/regionCommunities';

  /**
   * Retrieve list of effected region communities.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `eligibilityGetRegionCommunties()` instead.
   *
   * This method doesn't expect any request body.
   */
  eligibilityGetRegionCommunties$Response(params?: EligibilityGetRegionCommunties$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EffectedRegionCommunity>>> {
    return eligibilityGetRegionCommunties(this.http, this.rootUrl, params, context);
  }

  /**
   * Retrieve list of effected region communities.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `eligibilityGetRegionCommunties$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  eligibilityGetRegionCommunties(params?: EligibilityGetRegionCommunties$Params, context?: HttpContext): Observable<Array<EffectedRegionCommunity>> {
    return this.eligibilityGetRegionCommunties$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<EffectedRegionCommunity>>): Array<EffectedRegionCommunity> => r.body)
    );
  }

}
