/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { SecondaryApplicant } from '../models/secondary-applicant';
import { secondaryApplicantGetSecondaryApplicants } from '../fn/secondary-applicant/secondary-applicant-get-secondary-applicants';
import { SecondaryApplicantGetSecondaryApplicants$Params } from '../fn/secondary-applicant/secondary-applicant-get-secondary-applicants';
import { secondaryApplicantUpsertDeleteSecondaryApplicant } from '../fn/secondary-applicant/secondary-applicant-upsert-delete-secondary-applicant';
import { SecondaryApplicantUpsertDeleteSecondaryApplicant$Params } from '../fn/secondary-applicant/secondary-applicant-upsert-delete-secondary-applicant';

@Injectable({ providedIn: 'root' })
export class SecondaryApplicantService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `secondaryApplicantUpsertDeleteSecondaryApplicant()` */
  static readonly SecondaryApplicantUpsertDeleteSecondaryApplicantPath = '/api/secondaryapplicants';

  /**
   * Create / update / delete a secondary applicant.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `secondaryApplicantUpsertDeleteSecondaryApplicant()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  secondaryApplicantUpsertDeleteSecondaryApplicant$Response(params: SecondaryApplicantUpsertDeleteSecondaryApplicant$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return secondaryApplicantUpsertDeleteSecondaryApplicant(this.http, this.rootUrl, params, context);
  }

  /**
   * Create / update / delete a secondary applicant.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `secondaryApplicantUpsertDeleteSecondaryApplicant$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  secondaryApplicantUpsertDeleteSecondaryApplicant(params: SecondaryApplicantUpsertDeleteSecondaryApplicant$Params, context?: HttpContext): Observable<string> {
    return this.secondaryApplicantUpsertDeleteSecondaryApplicant$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `secondaryApplicantGetSecondaryApplicants()` */
  static readonly SecondaryApplicantGetSecondaryApplicantsPath = '/api/secondaryapplicants/byApplicationId';

  /**
   * Get a list of secondary applicants by id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `secondaryApplicantGetSecondaryApplicants()` instead.
   *
   * This method doesn't expect any request body.
   */
  secondaryApplicantGetSecondaryApplicants$Response(params?: SecondaryApplicantGetSecondaryApplicants$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SecondaryApplicant>>> {
    return secondaryApplicantGetSecondaryApplicants(this.http, this.rootUrl, params, context);
  }

  /**
   * Get a list of secondary applicants by id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `secondaryApplicantGetSecondaryApplicants$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  secondaryApplicantGetSecondaryApplicants(params?: SecondaryApplicantGetSecondaryApplicants$Params, context?: HttpContext): Observable<Array<SecondaryApplicant>> {
    return this.secondaryApplicantGetSecondaryApplicants$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<SecondaryApplicant>>): Array<SecondaryApplicant> => r.body)
    );
  }

}
