/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DisasterEvent } from '../../models/disaster-event';

export interface EligibilityGetOpenEvents$Params {
}

export function eligibilityGetOpenEvents(http: HttpClient, rootUrl: string, params?: EligibilityGetOpenEvents$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DisasterEvent>>> {
  const rb = new RequestBuilder(rootUrl, eligibilityGetOpenEvents.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<DisasterEvent>>;
    })
  );
}

eligibilityGetOpenEvents.PATH = '/api/eligibility/openEvents';
