#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMBC.Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum BcGoV_DocumentUrl_BcGoV_FileClassification
	{
		
		/// <summary>
		/// applies to the lowest level of classified government data. Confidential data requires less protection than top-secret or secret data. Disclosed confidential information can cause some harm to national security.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Confidential", 2, "#0000ff", "applies to the lowest level of classified government data. Confidential data requ" +
			"ires less protection than top-secret or secret data. Disclosed confidential info" +
			"rmation can cause some harm to national security.")]
		Confidential = 931490002,
		
		/// <summary>
		/// information that requires a high level of protection. The disclosure of this information can cause serious damage to national security.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Secret", 3, "#0000ff", "information that requires a high level of protection. The disclosure of this info" +
			"rmation can cause serious damage to national security.")]
		Secret = 931490003,
		
		/// <summary>
		/// includes all information that is not otherwise classified. However, it is still categorized as sensitive, which means it requires some protection. Disclosed SBU data may violate the privacy rights of citizens.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sensitive", 1, "#0000ff", "includes all information that is not otherwise classified. However, it is still c" +
			"ategorized as sensitive, which means it requires some protection. Disclosed SBU " +
			"data may violate the privacy rights of citizens.")]
		Sensitive = 931490001,
		
		/// <summary>
		/// information that requires the highest level of access control and protection. It is restricted to people with a “need to know” clearance. Disclosed top-secret data can threaten national security.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Top Secret", 4, "#0000ff", "information that requires the highest level of access control and protection. It " +
			"is restricted to people with a “need to know” clearance. Disclosed top-secret da" +
			"ta can threaten national security.")]
		TopSecret = 931490004,
		
		/// <summary>
		/// applies to data labeled as not sensitive. This data does not require any protection.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Unclassified", 0, "#0000ff", "applies to data labeled as not sensitive. This data does not require any protecti" +
			"on.")]
		Unclassified = 931490000,
	}
	
	/// <summary>
	/// Status of the Document Url
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum BcGoV_DocumentUrl_StateCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Active", 0)]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inactive", 1)]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Document Url
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum BcGoV_DocumentUrl_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Active", 0, "#0000ff")]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Error Creating Metadata", 1, "#0000ff")]
		ErrorCreatingMetadata = 222710000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Error Uploading to S3", 2, "#0000ff")]
		ErrorUploadingToS3 = 222710001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inactive", 3, "#0000ff")]
		Inactive = 2,
	}
	
	/// <summary>
	/// Stores document metadata information.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("bcgov_documenturl")]
	public partial class BcGoV_DocumentUrl : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the bcgov_documenturl entity
		/// </summary>
		public partial class Fields
		{
			public const string BcGoV_AppointmentId = "bcgov_appointmentid";
			public const string BcGoV_AppointmentIdName = "bcgov_appointmentidname";
			public const string BcGoV_CaseId = "bcgov_caseid";
			public const string BcGoV_CaseiDnaMe = "bcgov_caseidname";
			public const string BcGoV_Customer = "bcgov_customer";
			public const string BcGoV_CustomerName = "bcgov_customername";
			public const string BcGoV_CustomerYomiName = "bcgov_customeryominame";
			public const string BcGoV_DocumentUrlId = "bcgov_documenturlid";
			public const string Id = "bcgov_documenturlid";
			public const string BcGoV_EmailId = "bcgov_emailid";
			public const string BcGoV_EmailIdName = "bcgov_emailidname";
			public const string BcGoV_FaxId = "bcgov_faxid";
			public const string BcGoV_FaxIdName = "bcgov_faxidname";
			public const string BcGoV_FileClassification = "bcgov_fileclassification";
			public const string BcGoV_FileClassificationName = "bcgov_fileclassificationname";
			public const string BcGoV_FileExtension = "bcgov_fileextension";
			public const string BcGoV_Filename = "bcgov_filename";
			public const string BcGoV_FileSize = "bcgov_filesize";
			public const string BcGoV_LetterId = "bcgov_letterid";
			public const string BcGoV_LetterIdName = "bcgov_letteridname";
			public const string BcGoV_MimeType = "bcgov_mimetype";
			public const string BcGoV_OriginCode = "bcgov_origincode";
			public const string BcGoV_OriginCodename = "bcgov_origincodename";
			public const string BcGoV_PhoneCallId = "bcgov_phonecallid";
			public const string BcGoV_PhoneCalliDnaMe = "bcgov_phonecallidname";
			public const string BcGoV_ReceivedDate = "bcgov_receiveddate";
			public const string BcGoV_Size = "bcgov_size";
			public const string BcGoV_Tag1Id = "bcgov_tag1id";
			public const string BcGoV_Tag1IdName = "bcgov_tag1idname";
			public const string BcGoV_Tag2Id = "bcgov_tag2id";
			public const string BcGoV_Tag2IdName = "bcgov_tag2idname";
			public const string BcGoV_Tag3Id = "bcgov_tag3id";
			public const string BcGoV_Tag3IdName = "bcgov_tag3idname";
			public const string BcGoV_TaskId = "bcgov_taskid";
			public const string BcGoV_TaskIdName = "bcgov_taskidname";
			public const string BcGoV_Url = "bcgov_url";
			public const string CreatedBy = "createdby";
			public const string CreatedByName = "createdbyname";
			public const string CreatedByYomiName = "createdbyyominame";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CreatedOnBehalfByName = "createdonbehalfbyname";
			public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
			public const string DFA_AppApplication = "dfa_appapplication";
			public const string DFA_AppApplicationName = "dfa_appapplicationname";
			public const string DFA_AppealId = "dfa_appealid";
			public const string DFA_AppealIdName = "dfa_appealidname";
			public const string DFA_Category = "dfa_category";
			public const string DFA_ClaimAppeal = "dfa_claimappeal";
			public const string DFA_ClaimAppealName = "dfa_claimappealname";
			public const string DFA_DateUploaded = "dfa_dateuploaded";
			public const string DFA_Description = "dfa_description";
			public const string DFA_DFA_Appeal_BcGoV_DocumentUrl_AppealId = "dfa_dfa_appeal_bcgov_documenturl_AppealId";
			public const string DFA_DFA_ProjectClaim_BcGoV_DocumentUrl_RecoveryClaim = "dfa_dfa_projectclaim_bcgov_documenturl_RecoveryClaim";
			public const string DFA_ErrorMessage = "dfa_errormessage";
			public const string DFA_InvoiceAppeal = "dfa_invoiceappeal";
			public const string DFA_InvoiceAppealName = "dfa_invoiceappealname";
			public const string DFA_ModifiedBySpEmailAddress = "dfa_modifiedbyspemailaddress";
			public const string DFA_ModifiedBySpLogin = "dfa_modifiedbysplogin";
			public const string DFA_ModifiedOnSp = "dfa_modifiedonsp";
			public const string DFA_Project = "dfa_project";
			public const string DFA_ProjectName = "dfa_projectname";
			public const string DFA_RecoveryClaim = "dfa_recoveryclaim";
			public const string DFA_RecoveryClaimName = "dfa_recoveryclaimname";
			public const string DFA_RequiredDocumentType = "dfa_requireddocumenttype";
			public const string DFA_S3ValidationMetadataFailures = "dfa_s3validationmetadatafailures";
			public const string DFA_S3ValidationMetadataStatus = "dfa_s3validationmetadatastatus";
			public const string DFA_S3ValidationMetadataStatusName = "dfa_s3validationmetadatastatusname";
			public const string DFA_SpFileUrl = "dfa_spfileurl";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string Lk_BcGoV_DocumentUrl_CreatedBy = "lk_bcgov_documenturl_createdby";
			public const string Lk_BcGoV_DocumentUrl_CreatedOnBehalfBy = "lk_bcgov_documenturl_createdonbehalfby";
			public const string Lk_BcGoV_DocumentUrl_ModifiedBy = "lk_bcgov_documenturl_modifiedby";
			public const string Lk_BcGoV_DocumentUrl_ModifiedOnBehalfBy = "lk_bcgov_documenturl_modifiedonbehalfby";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedByName = "modifiedbyname";
			public const string ModifiedByYomiName = "modifiedbyyominame";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
			public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwnerIdName = "owneridname";
			public const string OwnerIdYomiName = "owneridyominame";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string StateCode = "statecode";
			public const string StateCodename = "statecodename";
			public const string StatusCode = "statuscode";
			public const string StatusCodename = "statuscodename";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string User_BcGoV_DocumentUrl = "user_bcgov_documenturl";
			public const string UtcConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public BcGoV_DocumentUrl(System.Guid id) : 
				base(EntityLogicalName, id)
		{
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public BcGoV_DocumentUrl(string keyName, object keyValue) : 
				base(EntityLogicalName, keyName, keyValue)
		{
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public BcGoV_DocumentUrl(Microsoft.Xrm.Sdk.KeyAttributeCollection keyAttributes) : 
				base(EntityLogicalName, keyAttributes)
		{
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public BcGoV_DocumentUrl() : 
				base(EntityLogicalName)
		{
		}
		
		public const string PrimaryIdAttribute = "bcgov_documenturlid";
		
		public const string PrimaryNameAttribute = "bcgov_filename";
		
		public const string EntitySchemaName = "bcgov_DocumentUrl";
		
		public const string EntityLogicalName = "bcgov_documenturl";
		
		public const string EntityLogicalCollectionName = "bcgov_documenturls";
		
		public const string EntitySetName = "bcgov_documenturls";
		
		/// <summary>
		/// Unique identifier for Appointment associated with Document.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bcgov_appointmentid")]
		public Microsoft.Xrm.Sdk.EntityReference BcGoV_AppointmentId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bcgov_appointmentid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("bcgov_appointmentid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bcgov_appointmentidname")]
		public string BcGoV_AppointmentIdName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("bcgov_appointmentid"))
				{
					return this.FormattedValues["bcgov_appointmentid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for Case associated with Document.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bcgov_caseid")]
		public Microsoft.Xrm.Sdk.EntityReference BcGoV_CaseId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bcgov_caseid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("bcgov_caseid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bcgov_caseidname")]
		public string BcGoV_CaseiDnaMe
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("bcgov_caseid"))
				{
					return this.FormattedValues["bcgov_caseid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for Customer associated with Document.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bcgov_customer")]
		public Microsoft.Xrm.Sdk.EntityReference BcGoV_Customer
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bcgov_customer");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("bcgov_customer", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bcgov_customername")]
		public string BcGoV_CustomerName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("bcgov_customer"))
				{
					return this.FormattedValues["bcgov_customer"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bcgov_customeryominame")]
		public string BcGoV_CustomerYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("bcgov_customer"))
				{
					return this.FormattedValues["bcgov_customer"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bcgov_documenturlid")]
		public System.Nullable<System.Guid> BcGoV_DocumentUrlId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("bcgov_documenturlid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("bcgov_documenturlid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bcgov_documenturlid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.BcGoV_DocumentUrlId = value;
			}
		}
		
		/// <summary>
		/// Unique identifier for Email associated with Document.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bcgov_emailid")]
		public Microsoft.Xrm.Sdk.EntityReference BcGoV_EmailId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bcgov_emailid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("bcgov_emailid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bcgov_emailidname")]
		public string BcGoV_EmailIdName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("bcgov_emailid"))
				{
					return this.FormattedValues["bcgov_emailid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for Fax associated with Document.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bcgov_faxid")]
		public Microsoft.Xrm.Sdk.EntityReference BcGoV_FaxId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bcgov_faxid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("bcgov_faxid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bcgov_faxidname")]
		public string BcGoV_FaxIdName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("bcgov_faxid"))
				{
					return this.FormattedValues["bcgov_faxid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bcgov_fileclassification")]
		public virtual BcGoV_DocumentUrl_BcGoV_FileClassification? BcGoV_FileClassification
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((BcGoV_DocumentUrl_BcGoV_FileClassification?)(EntityOptionSetEnum.GetEnum(this, "bcgov_fileclassification")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("bcgov_fileclassification", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bcgov_fileclassificationname")]
		public string BcGoV_FileClassificationName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("bcgov_fileclassification"))
				{
					return this.FormattedValues["bcgov_fileclassification"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// The file extension of the document.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bcgov_fileextension")]
		public string BcGoV_FileExtension
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("bcgov_fileextension");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("bcgov_fileextension", value);
			}
		}
		
		/// <summary>
		/// The name of the document.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bcgov_filename")]
		public string BcGoV_Filename
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("bcgov_filename");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("bcgov_filename", value);
			}
		}
		
		/// <summary>
		/// File Size of the Document.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bcgov_filesize")]
		public string BcGoV_FileSize
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("bcgov_filesize");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("bcgov_filesize", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for Letter associated with Document.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bcgov_letterid")]
		public Microsoft.Xrm.Sdk.EntityReference BcGoV_LetterId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bcgov_letterid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("bcgov_letterid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bcgov_letteridname")]
		public string BcGoV_LetterIdName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("bcgov_letterid"))
				{
					return this.FormattedValues["bcgov_letterid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bcgov_mimetype")]
		public string BcGoV_MimeType
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("bcgov_mimetype");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("bcgov_mimetype", value);
			}
		}
		
		/// <summary>
		/// Information that specifies the source of the Document, such as Web or email.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bcgov_origincode")]
		public virtual BcGoV_OriginCode? BcGoV_OriginCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((BcGoV_OriginCode?)(EntityOptionSetEnum.GetEnum(this, "bcgov_origincode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("bcgov_origincode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bcgov_origincodename")]
		public string BcGoV_OriginCodename
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("bcgov_origincode"))
				{
					return this.FormattedValues["bcgov_origincode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for Phone Call associated with Document.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bcgov_phonecallid")]
		public Microsoft.Xrm.Sdk.EntityReference BcGoV_PhoneCallId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bcgov_phonecallid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("bcgov_phonecallid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bcgov_phonecallidname")]
		public string BcGoV_PhoneCalliDnaMe
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("bcgov_phonecallid"))
				{
					return this.FormattedValues["bcgov_phonecallid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// The Date the document was uploaded or received.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bcgov_receiveddate")]
		public System.Nullable<System.DateTime> BcGoV_ReceivedDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("bcgov_receiveddate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("bcgov_receiveddate", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bcgov_size")]
		public System.Nullable<decimal> BcGoV_Size
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("bcgov_size");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("bcgov_size", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for Tag associated with Document.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bcgov_tag1id")]
		public Microsoft.Xrm.Sdk.EntityReference BcGoV_Tag1Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bcgov_tag1id");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("bcgov_tag1id", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bcgov_tag1idname")]
		public string BcGoV_Tag1IdName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("bcgov_tag1id"))
				{
					return this.FormattedValues["bcgov_tag1id"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for Tag associated with Document.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bcgov_tag2id")]
		public Microsoft.Xrm.Sdk.EntityReference BcGoV_Tag2Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bcgov_tag2id");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("bcgov_tag2id", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bcgov_tag2idname")]
		public string BcGoV_Tag2IdName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("bcgov_tag2id"))
				{
					return this.FormattedValues["bcgov_tag2id"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for Tag associated with Document.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bcgov_tag3id")]
		public Microsoft.Xrm.Sdk.EntityReference BcGoV_Tag3Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bcgov_tag3id");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("bcgov_tag3id", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bcgov_tag3idname")]
		public string BcGoV_Tag3IdName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("bcgov_tag3id"))
				{
					return this.FormattedValues["bcgov_tag3id"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for Task associated with Document.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bcgov_taskid")]
		public Microsoft.Xrm.Sdk.EntityReference BcGoV_TaskId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bcgov_taskid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("bcgov_taskid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bcgov_taskidname")]
		public string BcGoV_TaskIdName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("bcgov_taskid"))
				{
					return this.FormattedValues["bcgov_taskid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// The Url of the document on where it is stored.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bcgov_url")]
		public string BcGoV_Url
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("bcgov_url");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("bcgov_url", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyname")]
		public string CreatedByName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyyominame")]
		public string CreatedByYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("createdonbehalfby", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyname")]
		public string CreatedOnBehalfByName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
		public string CreatedOnBehalfByYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_appapplication")]
		public Microsoft.Xrm.Sdk.EntityReference DFA_AppApplication
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("dfa_appapplication");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_appapplication", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_appapplicationname")]
		public string DFA_AppApplicationName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_appapplication"))
				{
					return this.FormattedValues["dfa_appapplication"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_appealid")]
		public Microsoft.Xrm.Sdk.EntityReference DFA_AppealId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("dfa_appealid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_appealid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_appealidname")]
		public string DFA_AppealIdName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_appealid"))
				{
					return this.FormattedValues["dfa_appealid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_category")]
		public string DFA_Category
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("dfa_category");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_category", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_claimappeal")]
		public Microsoft.Xrm.Sdk.EntityReference DFA_ClaimAppeal
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("dfa_claimappeal");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_claimappeal", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_claimappealname")]
		public string DFA_ClaimAppealName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_claimappeal"))
				{
					return this.FormattedValues["dfa_claimappeal"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_dateuploaded")]
		public System.Nullable<System.DateTime> DFA_DateUploaded
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("dfa_dateuploaded");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_dateuploaded", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_description")]
		public string DFA_Description
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("dfa_description");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_description", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_errormessage")]
		public string DFA_ErrorMessage
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("dfa_errormessage");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_errormessage", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_invoiceappeal")]
		public Microsoft.Xrm.Sdk.EntityReference DFA_InvoiceAppeal
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("dfa_invoiceappeal");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_invoiceappeal", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_invoiceappealname")]
		public string DFA_InvoiceAppealName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_invoiceappeal"))
				{
					return this.FormattedValues["dfa_invoiceappeal"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_modifiedbyspemailaddress")]
		public string DFA_ModifiedBySpEmailAddress
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("dfa_modifiedbyspemailaddress");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_modifiedbyspemailaddress", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_modifiedbysplogin")]
		public string DFA_ModifiedBySpLogin
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("dfa_modifiedbysplogin");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_modifiedbysplogin", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_modifiedonsp")]
		public System.Nullable<System.DateTime> DFA_ModifiedOnSp
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("dfa_modifiedonsp");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_modifiedonsp", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_project")]
		public Microsoft.Xrm.Sdk.EntityReference DFA_Project
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("dfa_project");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_project", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_projectname")]
		public string DFA_ProjectName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_project"))
				{
					return this.FormattedValues["dfa_project"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_recoveryclaim")]
		public Microsoft.Xrm.Sdk.EntityReference DFA_RecoveryClaim
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("dfa_recoveryclaim");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_recoveryclaim", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_recoveryclaimname")]
		public string DFA_RecoveryClaimName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_recoveryclaim"))
				{
					return this.FormattedValues["dfa_recoveryclaim"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_requireddocumenttype")]
		public string DFA_RequiredDocumentType
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("dfa_requireddocumenttype");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_requireddocumenttype", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_s3validationmetadatafailures")]
		public string DFA_S3ValidationMetadataFailures
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("dfa_s3validationmetadatafailures");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_s3validationmetadatafailures", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_s3validationmetadatastatus")]
		public virtual DFA_DataValidationStatus? DFA_S3ValidationMetadataStatus
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((DFA_DataValidationStatus?)(EntityOptionSetEnum.GetEnum(this, "dfa_s3validationmetadatastatus")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_s3validationmetadatastatus", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_s3validationmetadatastatusname")]
		public string DFA_S3ValidationMetadataStatusName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_s3validationmetadatastatus"))
				{
					return this.FormattedValues["dfa_s3validationmetadatastatus"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_spfileurl")]
		public string DFA_SpFileUrl
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("dfa_spfileurl");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_spfileurl", value);
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("modifiedby", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyname")]
		public string ModifiedByName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyyominame")]
		public string ModifiedByYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("modifiedon", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("modifiedonbehalfby", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
		public string ModifiedOnBehalfByName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
		public string ModifiedOnBehalfByYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		/// <summary>
		/// Name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridname")]
		public string OwnerIdName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Yomi name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridyominame")]
		public string OwnerIdYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Document Url
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual BcGoV_DocumentUrl_StateCode? StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((BcGoV_DocumentUrl_StateCode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecodename")]
		public string StateCodename
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("statecode"))
				{
					return this.FormattedValues["statecode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Reason for the status of the Document Url
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual BcGoV_DocumentUrl_StatusCode? StatusCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((BcGoV_DocumentUrl_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscodename")]
		public string StatusCodename
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("statuscode"))
				{
					return this.FormattedValues["statuscode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UtcConversionTimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:1 dfa_dfa_appeal_bcgov_documenturl_AppealId
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_appealid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dfa_dfa_appeal_bcgov_documenturl_AppealId")]
		public EMBC.Database.Model.DFA_Appeal DFA_DFA_Appeal_BcGoV_DocumentUrl_AppealId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EMBC.Database.Model.DFA_Appeal>("dfa_dfa_appeal_bcgov_documenturl_AppealId", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<EMBC.Database.Model.DFA_Appeal>("dfa_dfa_appeal_bcgov_documenturl_AppealId", null, value);
			}
		}
		
		/// <summary>
		/// N:1 dfa_dfa_projectclaim_bcgov_documenturl_RecoveryClaim
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_recoveryclaim")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dfa_dfa_projectclaim_bcgov_documenturl_RecoveryClaim")]
		public EMBC.Database.Model.DFA_ProjectClaim DFA_DFA_ProjectClaim_BcGoV_DocumentUrl_RecoveryClaim
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EMBC.Database.Model.DFA_ProjectClaim>("dfa_dfa_projectclaim_bcgov_documenturl_RecoveryClaim", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<EMBC.Database.Model.DFA_ProjectClaim>("dfa_dfa_projectclaim_bcgov_documenturl_RecoveryClaim", null, value);
			}
		}
		
		/// <summary>
		/// N:1 lk_bcgov_documenturl_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_bcgov_documenturl_createdby")]
		public EMBC.Database.Model.SystemUser Lk_BcGoV_DocumentUrl_CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EMBC.Database.Model.SystemUser>("lk_bcgov_documenturl_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_bcgov_documenturl_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_bcgov_documenturl_createdonbehalfby")]
		public EMBC.Database.Model.SystemUser Lk_BcGoV_DocumentUrl_CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EMBC.Database.Model.SystemUser>("lk_bcgov_documenturl_createdonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<EMBC.Database.Model.SystemUser>("lk_bcgov_documenturl_createdonbehalfby", null, value);
			}
		}
		
		/// <summary>
		/// N:1 lk_bcgov_documenturl_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_bcgov_documenturl_modifiedby")]
		public EMBC.Database.Model.SystemUser Lk_BcGoV_DocumentUrl_ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EMBC.Database.Model.SystemUser>("lk_bcgov_documenturl_modifiedby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<EMBC.Database.Model.SystemUser>("lk_bcgov_documenturl_modifiedby", null, value);
			}
		}
		
		/// <summary>
		/// N:1 lk_bcgov_documenturl_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_bcgov_documenturl_modifiedonbehalfby")]
		public EMBC.Database.Model.SystemUser Lk_BcGoV_DocumentUrl_ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EMBC.Database.Model.SystemUser>("lk_bcgov_documenturl_modifiedonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<EMBC.Database.Model.SystemUser>("lk_bcgov_documenturl_modifiedonbehalfby", null, value);
			}
		}
		
		/// <summary>
		/// N:1 user_bcgov_documenturl
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_bcgov_documenturl")]
		public EMBC.Database.Model.SystemUser User_BcGoV_DocumentUrl
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EMBC.Database.Model.SystemUser>("user_bcgov_documenturl", null);
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public BcGoV_DocumentUrl(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (value != null && name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["bcgov_documenturlid"] = base.Id;
                        break;
                    case "bcgov_documenturlid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}
#pragma warning restore CS1591
