#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMBC.Database.Model
{
	
	
	/// <summary>
	/// Status of the Claim appeal
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum DFA_ClaimAppeal_StateCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Active", 0)]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inactive", 1)]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Claim appeal
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum DFA_ClaimAppeal_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Closed", 2, "#0000ff")]
		Closed = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("In Progress", 1, "#0000ff")]
		InProgress = 222710000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Submitted", 0, "#0000ff")]
		Submitted = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("dfa_claimappeal")]
	public partial class DFA_ClaimAppeal : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the dfa_claimappeal entity
		/// </summary>
		public partial class Fields
		{
			public const string Bpf_DFA_ClaimAppeal_DFA_ClaimAppealBpf = "Bpf_DFA_ClaimAppeal_DFA_ClaimAppealBpf";
			public const string CreatedBy = "createdby";
			public const string CreatedByName = "createdbyname";
			public const string CreatedByYomiName = "createdbyyominame";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CreatedOnBehalfByName = "createdonbehalfbyname";
			public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
			public const string DFA_AdditionalInfoRequested = "dfa_additionalinforequested";
			public const string DFA_AdditionalInfoRequestedName = "dfa_additionalinforequestedname";
			public const string DFA_AllSupportingAndProofOfPaymentDocsStamped = "dfa_allsupportingandproofofpaymentdocsstamped";
			public const string DFA_AllSupportingAndProofOfPaymentDocsStampedName = "dfa_allsupportingandproofofpaymentdocsstampedname";
			public const string DFA_AllSupportingDocsStamped = "dfa_allsupportingdocsstamped";
			public const string DFA_AllSupportingDocsStampedName = "dfa_allsupportingdocsstampedname";
			public const string DFA_AppealDecision = "dfa_appealdecision";
			public const string DFA_AppealDecisionCommentsAdded = "dfa_appealdecisioncommentsadded";
			public const string DFA_AppealDecisionCommentsAddedName = "dfa_appealdecisioncommentsaddedname";
			public const string DFA_AppealDecisionDate = "dfa_appealdecisiondate";
			public const string DFA_AppealDecisionName = "dfa_appealdecisionname";
			public const string DFA_AppealDecisionReason = "dfa_appealdecisionreason";
			public const string DFA_AppealReason = "dfa_appealreason";
			public const string DFA_AssignedTo = "dfa_assignedto";
			public const string DFA_AssignedToAdjudicator = "dfa_assignedtoadjudicator";
			public const string DFA_AssignedToAdjudicatorName = "dfa_assignedtoadjudicatorname";
			public const string DFA_AssignedToEvaluator = "dfa_assignedtoevaluator";
			public const string DFA_AssignedToEvaluatorName = "dfa_assignedtoevaluatorname";
			public const string DFA_AssignedToName = "dfa_assignedtoname";
			public const string DFA_AssignedToYomiName = "dfa_assignedtoyominame";
			public const string DFA_AssignmentComment = "dfa_assignmentcomment";
			public const string DFA_Case = "dfa_case";
			public const string DFA_CaseMaterialsReviewed = "dfa_casematerialsreviewed";
			public const string DFA_CaseMaterialsReviewedName = "dfa_casematerialsreviewedname";
			public const string DFA_CaseName = "dfa_casename";
			public const string DFA_CheckLGiGbAppealDecisionLetter = "dfa_checklgigbappealdecisionletter";
			public const string DFA_CheckLGiGbAppealDecisionLetterName = "dfa_checklgigbappealdecisionlettername";
			public const string DFA_ClaimAppealId = "dfa_claimappealid";
			public const string Id = "dfa_claimappealid";
			public const string DFA_CreatedOnPortal = "dfa_createdonportal";
			public const string DFA_CreatedOnPortalName = "dfa_createdonportalname";
			public const string DFA_DateAppealReceived = "dfa_dateappealreceived";
			public const string DFA_DateAssigned = "dfa_dateassigned";
			public const string DFA_DateAssignedToEngineer = "dfa_dateassignedtoengineer";
			public const string DFA_DateEngineerReportReceived = "dfa_dateengineerreportreceived";
			public const string DFA_DFA_ClaimAppeal_BcGoV_DocumentUrl_ClaimAppeal = "DFA_DFA_ClaimAppeal_BcGoV_DocumentUrl_ClaimAppeal";
			public const string DFA_DFA_ClaimAppeal_DFA_InvoiceAppeal_ClaimAppeal = "DFA_DFA_ClaimAppeal_DFA_InvoiceAppeal_ClaimAppeal";
			public const string DFA_DFA_Event_DFA_ClaimAppeal_Event = "dfa_dfa_event_dfa_claimappeal_Event";
			public const string DFA_DFA_Project_DFA_ClaimAppeal_Project = "dfa_dfa_project_dfa_claimappeal_Project";
			public const string DFA_DFA_ProjectClaim_DFA_ClaimAppeal_OriginClaim = "dfa_dfa_projectclaim_dfa_claimappeal_OriginClaim";
			public const string DFA_Event = "dfa_event";
			public const string DFA_EventName = "dfa_eventname";
			public const string DFA_ExpensesMatchApproVedicRP = "dfa_expensesmatchapprovedicrp";
			public const string DFA_ExpensesMatchApproVedicRPName = "dfa_expensesmatchapprovedicrpname";
			public const string DFA_ExtensionRequestDeadline = "dfa_extensionrequestdeadline";
			public const string DFA_GeneraterDAndDecisionLetter = "dfa_generaterdanddecisionletter";
			public const string DFA_GeneraterDAndDecisionLetterName = "dfa_generaterdanddecisionlettername";
			public const string DFA_INeApprovals = "dfa_ineapprovals";
			public const string DFA_INeApprovalsName = "dfa_ineapprovalsname";
			public const string DFA_InformationRequestDueDate = "dfa_informationrequestduedate";
			public const string DFA_MandatoryDocsInOrder = "dfa_mandatorydocsinorder";
			public const string DFA_MandatoryDocsInOrderName = "dfa_mandatorydocsinordername";
			public const string DFA_Name = "dfa_name";
			public const string DFA_OriginClaim = "dfa_originclaim";
			public const string DFA_OriginClaimName = "dfa_originclaimname";
			public const string DFA_PrimaryContact = "dfa_primarycontact";
			public const string DFA_PrimaryContactName = "dfa_primarycontactname";
			public const string DFA_PrimaryContactYomiName = "dfa_primarycontactyominame";
			public const string DFA_ProgramPolicyComments = "dfa_programpolicycomments";
			public const string DFA_ProgramPolicyUpdateRequired = "dfa_programpolicyupdaterequired";
			public const string DFA_ProgramPolicyUpdateRequiredName = "dfa_programpolicyupdaterequiredname";
			public const string DFA_Project = "dfa_project";
			public const string DFA_ProjectName = "dfa_projectname";
			public const string DFA_RAFtTimelineNoteAdded = "dfa_rafttimelinenoteadded";
			public const string DFA_RAFtTimelineNoteAddedName = "dfa_rafttimelinenoteaddedname";
			public const string DFA_RequiresDecisionNote = "dfa_requiresdecisionnote";
			public const string DFA_RequiresDecisionNoteName = "dfa_requiresdecisionnotename";
			public const string DFA_SendLGiGbAppealDecisionLetter = "dfa_sendlgigbappealdecisionletter";
			public const string DFA_SendLGiGbAppealDecisionLetterName = "dfa_sendlgigbappealdecisionlettername";
			public const string DFA_SubmittedForDirectorReview = "dfa_submittedfordirectorreview";
			public const string DFA_SubmittedForDirectorReviewName = "dfa_submittedfordirectorreviewname";
			public const string DFA_SystemUser_DFA_ClaimAppeal_AssignedTo = "dfa_systemuser_dfa_claimappeal_AssignedTo";
			public const string DFA_Today = "dfa_today";
			public const string DFA_WaitingOnLegal = "dfa_waitingonlegal";
			public const string DFA_WaitingOnLegalName = "dfa_waitingonlegalname";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string Lk_DFA_ClaimAppeal_CreatedBy = "lk_dfa_claimappeal_createdby";
			public const string Lk_DFA_ClaimAppeal_CreatedOnBehalfBy = "lk_dfa_claimappeal_createdonbehalfby";
			public const string Lk_DFA_ClaimAppeal_ModifiedBy = "lk_dfa_claimappeal_modifiedby";
			public const string Lk_DFA_ClaimAppeal_ModifiedOnBehalfBy = "lk_dfa_claimappeal_modifiedonbehalfby";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedByName = "modifiedbyname";
			public const string ModifiedByYomiName = "modifiedbyyominame";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
			public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwnerIdName = "owneridname";
			public const string OwnerIdYomiName = "owneridyominame";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string ProcessId = "processid";
			public const string ProcessStage_DFA_ClaimAppeal = "processstage_dfa_claimappeal";
			public const string StageId = "stageid";
			public const string StateCode = "statecode";
			public const string StateCodename = "statecodename";
			public const string StatusCode = "statuscode";
			public const string StatusCodename = "statuscodename";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string TraversedPath = "traversedpath";
			public const string User_DFA_ClaimAppeal = "user_dfa_claimappeal";
			public const string UtcConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public DFA_ClaimAppeal(System.Guid id) : 
				base(EntityLogicalName, id)
		{
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public DFA_ClaimAppeal(string keyName, object keyValue) : 
				base(EntityLogicalName, keyName, keyValue)
		{
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public DFA_ClaimAppeal(Microsoft.Xrm.Sdk.KeyAttributeCollection keyAttributes) : 
				base(EntityLogicalName, keyAttributes)
		{
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public DFA_ClaimAppeal() : 
				base(EntityLogicalName)
		{
		}
		
		public const string PrimaryIdAttribute = "dfa_claimappealid";
		
		public const string PrimaryNameAttribute = "dfa_name";
		
		public const string EntitySchemaName = "dfa_claimappeal";
		
		public const string EntityLogicalName = "dfa_claimappeal";
		
		public const string EntityLogicalCollectionName = "dfa_claimappeals";
		
		public const string EntitySetName = "dfa_claimappeals";
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyname")]
		public string CreatedByName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyyominame")]
		public string CreatedByYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("createdonbehalfby", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyname")]
		public string CreatedOnBehalfByName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
		public string CreatedOnBehalfByYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_additionalinforequested")]
		public System.Nullable<bool> DFA_AdditionalInfoRequested
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_additionalinforequested");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_additionalinforequested", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_additionalinforequestedname")]
		public string DFA_AdditionalInfoRequestedName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_additionalinforequested"))
				{
					return this.FormattedValues["dfa_additionalinforequested"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_allsupportingandproofofpaymentdocsstamped")]
		public System.Nullable<bool> DFA_AllSupportingAndProofOfPaymentDocsStamped
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_allsupportingandproofofpaymentdocsstamped");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_allsupportingandproofofpaymentdocsstamped", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_allsupportingandproofofpaymentdocsstampedname")]
		public string DFA_AllSupportingAndProofOfPaymentDocsStampedName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_allsupportingandproofofpaymentdocsstamped"))
				{
					return this.FormattedValues["dfa_allsupportingandproofofpaymentdocsstamped"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_allsupportingdocsstamped")]
		public System.Nullable<bool> DFA_AllSupportingDocsStamped
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_allsupportingdocsstamped");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_allsupportingdocsstamped", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_allsupportingdocsstampedname")]
		public string DFA_AllSupportingDocsStampedName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_allsupportingdocsstamped"))
				{
					return this.FormattedValues["dfa_allsupportingdocsstamped"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_appealdecision")]
		public virtual DFA_AppealDecision? DFA_AppealDecision
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((DFA_AppealDecision?)(EntityOptionSetEnum.GetEnum(this, "dfa_appealdecision")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_appealdecision", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_appealdecisioncommentsadded")]
		public System.Nullable<bool> DFA_AppealDecisionCommentsAdded
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_appealdecisioncommentsadded");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_appealdecisioncommentsadded", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_appealdecisioncommentsaddedname")]
		public string DFA_AppealDecisionCommentsAddedName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_appealdecisioncommentsadded"))
				{
					return this.FormattedValues["dfa_appealdecisioncommentsadded"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_appealdecisiondate")]
		public System.Nullable<System.DateTime> DFA_AppealDecisionDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("dfa_appealdecisiondate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_appealdecisiondate", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_appealdecisionname")]
		public string DFA_AppealDecisionName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_appealdecision"))
				{
					return this.FormattedValues["dfa_appealdecision"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_appealdecisionreason")]
		public string DFA_AppealDecisionReason
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("dfa_appealdecisionreason");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_appealdecisionreason", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_appealreason")]
		public string DFA_AppealReason
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("dfa_appealreason");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_appealreason", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_assignedto")]
		public Microsoft.Xrm.Sdk.EntityReference DFA_AssignedTo
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("dfa_assignedto");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_assignedto", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_assignedtoadjudicator")]
		public System.Nullable<bool> DFA_AssignedToAdjudicator
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_assignedtoadjudicator");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_assignedtoadjudicator", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_assignedtoadjudicatorname")]
		public string DFA_AssignedToAdjudicatorName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_assignedtoadjudicator"))
				{
					return this.FormattedValues["dfa_assignedtoadjudicator"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_assignedtoevaluator")]
		public System.Nullable<bool> DFA_AssignedToEvaluator
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_assignedtoevaluator");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_assignedtoevaluator", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_assignedtoevaluatorname")]
		public string DFA_AssignedToEvaluatorName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_assignedtoevaluator"))
				{
					return this.FormattedValues["dfa_assignedtoevaluator"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_assignedtoname")]
		public string DFA_AssignedToName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_assignedto"))
				{
					return this.FormattedValues["dfa_assignedto"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_assignedtoyominame")]
		public string DFA_AssignedToYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_assignedto"))
				{
					return this.FormattedValues["dfa_assignedto"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_assignmentcomment")]
		public string DFA_AssignmentComment
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("dfa_assignmentcomment");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_assignmentcomment", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_case")]
		public Microsoft.Xrm.Sdk.EntityReference DFA_Case
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("dfa_case");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_case", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_casematerialsreviewed")]
		public System.Nullable<bool> DFA_CaseMaterialsReviewed
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_casematerialsreviewed");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_casematerialsreviewed", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_casematerialsreviewedname")]
		public string DFA_CaseMaterialsReviewedName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_casematerialsreviewed"))
				{
					return this.FormattedValues["dfa_casematerialsreviewed"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_casename")]
		public string DFA_CaseName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_case"))
				{
					return this.FormattedValues["dfa_case"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_checklgigbappealdecisionletter")]
		public System.Nullable<bool> DFA_CheckLGiGbAppealDecisionLetter
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_checklgigbappealdecisionletter");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_checklgigbappealdecisionletter", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_checklgigbappealdecisionlettername")]
		public string DFA_CheckLGiGbAppealDecisionLetterName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_checklgigbappealdecisionletter"))
				{
					return this.FormattedValues["dfa_checklgigbappealdecisionletter"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_claimappealid")]
		public System.Nullable<System.Guid> DFA_ClaimAppealId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("dfa_claimappealid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_claimappealid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_claimappealid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.DFA_ClaimAppealId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_createdonportal")]
		public System.Nullable<bool> DFA_CreatedOnPortal
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_createdonportal");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_createdonportal", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_createdonportalname")]
		public string DFA_CreatedOnPortalName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_createdonportal"))
				{
					return this.FormattedValues["dfa_createdonportal"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_dateappealreceived")]
		public System.Nullable<System.DateTime> DFA_DateAppealReceived
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("dfa_dateappealreceived");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_dateappealreceived", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_dateassigned")]
		public System.Nullable<System.DateTime> DFA_DateAssigned
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("dfa_dateassigned");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_dateassigned", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_dateassignedtoengineer")]
		public System.Nullable<System.DateTime> DFA_DateAssignedToEngineer
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("dfa_dateassignedtoengineer");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_dateassignedtoengineer", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_dateengineerreportreceived")]
		public System.Nullable<System.DateTime> DFA_DateEngineerReportReceived
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("dfa_dateengineerreportreceived");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_dateengineerreportreceived", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_event")]
		public Microsoft.Xrm.Sdk.EntityReference DFA_Event
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("dfa_event");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_event", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_eventname")]
		public string DFA_EventName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_event"))
				{
					return this.FormattedValues["dfa_event"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_expensesmatchapprovedicrp")]
		public System.Nullable<bool> DFA_ExpensesMatchApproVedicRP
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_expensesmatchapprovedicrp");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_expensesmatchapprovedicrp", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_expensesmatchapprovedicrpname")]
		public string DFA_ExpensesMatchApproVedicRPName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_expensesmatchapprovedicrp"))
				{
					return this.FormattedValues["dfa_expensesmatchapprovedicrp"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_extensionrequestdeadline")]
		public System.Nullable<System.DateTime> DFA_ExtensionRequestDeadline
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("dfa_extensionrequestdeadline");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_extensionrequestdeadline", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_generaterdanddecisionletter")]
		public System.Nullable<bool> DFA_GeneraterDAndDecisionLetter
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_generaterdanddecisionletter");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_generaterdanddecisionletter", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_generaterdanddecisionlettername")]
		public string DFA_GeneraterDAndDecisionLetterName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_generaterdanddecisionletter"))
				{
					return this.FormattedValues["dfa_generaterdanddecisionletter"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_ineapprovals")]
		public System.Nullable<bool> DFA_INeApprovals
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_ineapprovals");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_ineapprovals", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_ineapprovalsname")]
		public string DFA_INeApprovalsName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_ineapprovals"))
				{
					return this.FormattedValues["dfa_ineapprovals"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_informationrequestduedate")]
		public System.Nullable<System.DateTime> DFA_InformationRequestDueDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("dfa_informationrequestduedate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_informationrequestduedate", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_mandatorydocsinorder")]
		public System.Nullable<bool> DFA_MandatoryDocsInOrder
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_mandatorydocsinorder");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_mandatorydocsinorder", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_mandatorydocsinordername")]
		public string DFA_MandatoryDocsInOrderName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_mandatorydocsinorder"))
				{
					return this.FormattedValues["dfa_mandatorydocsinorder"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// The name of the custom entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_name")]
		public string DFA_Name
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("dfa_name");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_name", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_originclaim")]
		public Microsoft.Xrm.Sdk.EntityReference DFA_OriginClaim
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("dfa_originclaim");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_originclaim", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_originclaimname")]
		public string DFA_OriginClaimName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_originclaim"))
				{
					return this.FormattedValues["dfa_originclaim"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_primarycontact")]
		public Microsoft.Xrm.Sdk.EntityReference DFA_PrimaryContact
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("dfa_primarycontact");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_primarycontact", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_primarycontactname")]
		public string DFA_PrimaryContactName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_primarycontact"))
				{
					return this.FormattedValues["dfa_primarycontact"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_primarycontactyominame")]
		public string DFA_PrimaryContactYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_primarycontact"))
				{
					return this.FormattedValues["dfa_primarycontact"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_programpolicycomments")]
		public string DFA_ProgramPolicyComments
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("dfa_programpolicycomments");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_programpolicycomments", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_programpolicyupdaterequired")]
		public System.Nullable<bool> DFA_ProgramPolicyUpdateRequired
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_programpolicyupdaterequired");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_programpolicyupdaterequired", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_programpolicyupdaterequiredname")]
		public string DFA_ProgramPolicyUpdateRequiredName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_programpolicyupdaterequired"))
				{
					return this.FormattedValues["dfa_programpolicyupdaterequired"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_project")]
		public Microsoft.Xrm.Sdk.EntityReference DFA_Project
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("dfa_project");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_project", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_projectname")]
		public string DFA_ProjectName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_project"))
				{
					return this.FormattedValues["dfa_project"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_rafttimelinenoteadded")]
		public System.Nullable<bool> DFA_RAFtTimelineNoteAdded
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_rafttimelinenoteadded");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_rafttimelinenoteadded", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_rafttimelinenoteaddedname")]
		public string DFA_RAFtTimelineNoteAddedName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_rafttimelinenoteadded"))
				{
					return this.FormattedValues["dfa_rafttimelinenoteadded"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_requiresdecisionnote")]
		public System.Nullable<bool> DFA_RequiresDecisionNote
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_requiresdecisionnote");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_requiresdecisionnote", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_requiresdecisionnotename")]
		public string DFA_RequiresDecisionNoteName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_requiresdecisionnote"))
				{
					return this.FormattedValues["dfa_requiresdecisionnote"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_sendlgigbappealdecisionletter")]
		public System.Nullable<bool> DFA_SendLGiGbAppealDecisionLetter
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_sendlgigbappealdecisionletter");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_sendlgigbappealdecisionletter", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_sendlgigbappealdecisionlettername")]
		public string DFA_SendLGiGbAppealDecisionLetterName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_sendlgigbappealdecisionletter"))
				{
					return this.FormattedValues["dfa_sendlgigbappealdecisionletter"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_submittedfordirectorreview")]
		public System.Nullable<bool> DFA_SubmittedForDirectorReview
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_submittedfordirectorreview");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_submittedfordirectorreview", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_submittedfordirectorreviewname")]
		public string DFA_SubmittedForDirectorReviewName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_submittedfordirectorreview"))
				{
					return this.FormattedValues["dfa_submittedfordirectorreview"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_today")]
		public System.Nullable<System.DateTime> DFA_Today
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("dfa_today");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_today", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_waitingonlegal")]
		public System.Nullable<bool> DFA_WaitingOnLegal
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_waitingonlegal");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_waitingonlegal", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_waitingonlegalname")]
		public string DFA_WaitingOnLegalName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_waitingonlegal"))
				{
					return this.FormattedValues["dfa_waitingonlegal"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyname")]
		public string ModifiedByName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyyominame")]
		public string ModifiedByYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("modifiedonbehalfby", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
		public string ModifiedOnBehalfByName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
		public string ModifiedOnBehalfByYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		/// <summary>
		/// Name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridname")]
		public string OwnerIdName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Yomi name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridyominame")]
		public string OwnerIdYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Contains the id of the process associated with the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processid")]
		public System.Nullable<System.Guid> ProcessId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("processid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("processid", value);
			}
		}
		
		/// <summary>
		/// Contains the id of the stage where the entity is located.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("stageid")]
		public System.Nullable<System.Guid> StageId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("stageid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("stageid", value);
			}
		}
		
		/// <summary>
		/// Status of the Claim appeal
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual DFA_ClaimAppeal_StateCode? StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((DFA_ClaimAppeal_StateCode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecodename")]
		public string StateCodename
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("statecode"))
				{
					return this.FormattedValues["statecode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Reason for the status of the Claim appeal
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual DFA_ClaimAppeal_StatusCode? StatusCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((DFA_ClaimAppeal_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscodename")]
		public string StatusCodename
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("statuscode"))
				{
					return this.FormattedValues["statuscode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// A comma separated list of string values representing the unique identifiers of stages in a Business Process Flow Instance in the order that they occur.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("traversedpath")]
		public string TraversedPath
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("traversedpath");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("traversedpath", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UtcConversionTimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N bpf_dfa_claimappeal_dfa_claimappealbpf
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bpf_dfa_claimappeal_dfa_claimappealbpf")]
		public System.Collections.Generic.IEnumerable<EMBC.Database.Model.DFA_ClaimAppealBpf> Bpf_DFA_ClaimAppeal_DFA_ClaimAppealBpf
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<EMBC.Database.Model.DFA_ClaimAppealBpf>("bpf_dfa_claimappeal_dfa_claimappealbpf", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntities<EMBC.Database.Model.DFA_ClaimAppealBpf>("bpf_dfa_claimappeal_dfa_claimappealbpf", null, value);
			}
		}
		
		/// <summary>
		/// 1:N dfa_dfa_claimappeal_bcgov_documenturl_ClaimAppeal
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dfa_dfa_claimappeal_bcgov_documenturl_ClaimAppeal")]
		public System.Collections.Generic.IEnumerable<EMBC.Database.Model.BcGoV_DocumentUrl> DFA_DFA_ClaimAppeal_BcGoV_DocumentUrl_ClaimAppeal
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<EMBC.Database.Model.BcGoV_DocumentUrl>("dfa_dfa_claimappeal_bcgov_documenturl_ClaimAppeal", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntities<EMBC.Database.Model.BcGoV_DocumentUrl>("dfa_dfa_claimappeal_bcgov_documenturl_ClaimAppeal", null, value);
			}
		}
		
		/// <summary>
		/// 1:N dfa_dfa_claimappeal_dfa_invoiceappeal_ClaimAppeal
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dfa_dfa_claimappeal_dfa_invoiceappeal_ClaimAppeal")]
		public System.Collections.Generic.IEnumerable<EMBC.Database.Model.DFA_InvoiceAppeal> DFA_DFA_ClaimAppeal_DFA_InvoiceAppeal_ClaimAppeal
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<EMBC.Database.Model.DFA_InvoiceAppeal>("dfa_dfa_claimappeal_dfa_invoiceappeal_ClaimAppeal", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntities<EMBC.Database.Model.DFA_InvoiceAppeal>("dfa_dfa_claimappeal_dfa_invoiceappeal_ClaimAppeal", null, value);
			}
		}
		
		/// <summary>
		/// N:1 dfa_dfa_event_dfa_claimappeal_Event
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_event")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dfa_dfa_event_dfa_claimappeal_Event")]
		public EMBC.Database.Model.DFA_Event DFA_DFA_Event_DFA_ClaimAppeal_Event
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EMBC.Database.Model.DFA_Event>("dfa_dfa_event_dfa_claimappeal_Event", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<EMBC.Database.Model.DFA_Event>("dfa_dfa_event_dfa_claimappeal_Event", null, value);
			}
		}
		
		/// <summary>
		/// N:1 dfa_dfa_project_dfa_claimappeal_Project
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_project")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dfa_dfa_project_dfa_claimappeal_Project")]
		public EMBC.Database.Model.DFA_Project DFA_DFA_Project_DFA_ClaimAppeal_Project
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EMBC.Database.Model.DFA_Project>("dfa_dfa_project_dfa_claimappeal_Project", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<EMBC.Database.Model.DFA_Project>("dfa_dfa_project_dfa_claimappeal_Project", null, value);
			}
		}
		
		/// <summary>
		/// N:1 dfa_dfa_projectclaim_dfa_claimappeal_OriginClaim
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_originclaim")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dfa_dfa_projectclaim_dfa_claimappeal_OriginClaim")]
		public EMBC.Database.Model.DFA_ProjectClaim DFA_DFA_ProjectClaim_DFA_ClaimAppeal_OriginClaim
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EMBC.Database.Model.DFA_ProjectClaim>("dfa_dfa_projectclaim_dfa_claimappeal_OriginClaim", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<EMBC.Database.Model.DFA_ProjectClaim>("dfa_dfa_projectclaim_dfa_claimappeal_OriginClaim", null, value);
			}
		}
		
		/// <summary>
		/// N:1 dfa_systemuser_dfa_claimappeal_AssignedTo
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_assignedto")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dfa_systemuser_dfa_claimappeal_AssignedTo")]
		public EMBC.Database.Model.SystemUser DFA_SystemUser_DFA_ClaimAppeal_AssignedTo
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EMBC.Database.Model.SystemUser>("dfa_systemuser_dfa_claimappeal_AssignedTo", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<EMBC.Database.Model.SystemUser>("dfa_systemuser_dfa_claimappeal_AssignedTo", null, value);
			}
		}
		
		/// <summary>
		/// N:1 lk_dfa_claimappeal_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_dfa_claimappeal_createdby")]
		public EMBC.Database.Model.SystemUser Lk_DFA_ClaimAppeal_CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EMBC.Database.Model.SystemUser>("lk_dfa_claimappeal_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_dfa_claimappeal_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_dfa_claimappeal_createdonbehalfby")]
		public EMBC.Database.Model.SystemUser Lk_DFA_ClaimAppeal_CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EMBC.Database.Model.SystemUser>("lk_dfa_claimappeal_createdonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<EMBC.Database.Model.SystemUser>("lk_dfa_claimappeal_createdonbehalfby", null, value);
			}
		}
		
		/// <summary>
		/// N:1 lk_dfa_claimappeal_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_dfa_claimappeal_modifiedby")]
		public EMBC.Database.Model.SystemUser Lk_DFA_ClaimAppeal_ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EMBC.Database.Model.SystemUser>("lk_dfa_claimappeal_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_dfa_claimappeal_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_dfa_claimappeal_modifiedonbehalfby")]
		public EMBC.Database.Model.SystemUser Lk_DFA_ClaimAppeal_ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EMBC.Database.Model.SystemUser>("lk_dfa_claimappeal_modifiedonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<EMBC.Database.Model.SystemUser>("lk_dfa_claimappeal_modifiedonbehalfby", null, value);
			}
		}
		
		/// <summary>
		/// N:1 processstage_dfa_claimappeal
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("stageid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("processstage_dfa_claimappeal")]
		public EMBC.Database.Model.ProcessStage ProcessStage_DFA_ClaimAppeal
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EMBC.Database.Model.ProcessStage>("processstage_dfa_claimappeal", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<EMBC.Database.Model.ProcessStage>("processstage_dfa_claimappeal", null, value);
			}
		}
		
		/// <summary>
		/// N:1 user_dfa_claimappeal
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_dfa_claimappeal")]
		public EMBC.Database.Model.SystemUser User_DFA_ClaimAppeal
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EMBC.Database.Model.SystemUser>("user_dfa_claimappeal", null);
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public DFA_ClaimAppeal(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (value != null && name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["dfa_claimappealid"] = base.Id;
                        break;
                    case "dfa_claimappealid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}
#pragma warning restore CS1591
