#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMBC.Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum DFA_ProjectAmendment_DFA_AdditionalProjectCostDecision
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Approved", 0, "#0000ff")]
		Approved = 222710000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Approved with Exclusions", 1, "#0000ff")]
		ApprovedWithExclusions = 222710001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Ineligible", 2, "#0000ff")]
		Ineligible = 222710002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Withdrawn", 3, "#0000ff")]
		Withdrawn = 222710003,
	}
	
	/// <summary>
	/// Status of the Project Amendment
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum DFA_ProjectAmendment_StateCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Active", 0)]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inactive", 1)]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Project Amendment
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum DFA_ProjectAmendment_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Adjudicator", 3, "#0000ff")]
		Adjudicator = 222710002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Approval Pending", 2, "#0000ff")]
		ApprovalPending = 222710001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Closed", 8, "#0000ff")]
		Closed = 222710007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Compliance Check", 4, "#0000ff")]
		ComplianceCheck = 222710003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Created", 0, "#0000ff")]
		Created = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Decision Made", 7, "#0000ff")]
		DecisionMade = 222710006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Expense Authority", 6, "#0000ff")]
		ExpenseAuthority = 222710005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inactive", 9, "#0000ff")]
		Inactive = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Qualified Receiver", 5, "#0000ff")]
		QualifiedReceiver = 222710004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Under Review", 1, "#0000ff")]
		UnderReview = 222710000,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("dfa_projectamendment")]
	public partial class DFA_ProjectAmendment : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the dfa_projectamendment entity
		/// </summary>
		public partial class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedByName = "createdbyname";
			public const string CreatedByYomiName = "createdbyyominame";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CreatedOnBehalfByName = "createdonbehalfbyname";
			public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
			public const string DFA_AdditionalProjectCostDecision = "dfa_additionalprojectcostdecision";
			public const string DFA_AdditionalProjectCostDecisionName = "dfa_additionalprojectcostdecisionname";
			public const string DFA_Adjudication = "dfa_adjudication";
			public const string DFA_AdjudicationName = "dfa_adjudicationname";
			public const string DFA_AdjudicatorAdditionalInfoRequested = "dfa_adjudicatoradditionalinforequested";
			public const string DFA_AdjudicatorAdditionalInfoRequestedName = "dfa_adjudicatoradditionalinforequestedname";
			public const string DFA_AdjudicatorAdjustmentsForIGbLetter = "dfa_adjudicatoradjustmentsforigbletter";
			public const string DFA_AdjudicatorAdjustmentsForIGbLetterName = "dfa_adjudicatoradjustmentsforigblettername";
			public const string DFA_AdjudicatorBackupDocuments = "dfa_adjudicatorbackupdocuments";
			public const string DFA_AdjudicatorBackupDocumentsName = "dfa_adjudicatorbackupdocumentsname";
			public const string DFA_AdjudicatorEligibleProjectsCope = "dfa_adjudicatoreligibleprojectscope";
			public const string DFA_AdjudicatorEligibleProjectsCopeName = "dfa_adjudicatoreligibleprojectscopename";
			public const string DFA_AdjudicatorGenerateApprovalLetter = "dfa_adjudicatorgenerateapprovalletter";
			public const string DFA_AdjudicatorGenerateApprovalLetterName = "dfa_adjudicatorgenerateapprovallettername";
			public const string DFA_AdjudicatorPreexistingCondition = "dfa_adjudicatorpreexistingcondition";
			public const string DFA_AdjudicatorPreexistingConditionName = "dfa_adjudicatorpreexistingconditionname";
			public const string DFA_AdjudicatorsTampaLlDocs = "dfa_adjudicatorstampalldocs";
			public const string DFA_AdjudicatorsTampaLlDocsName = "dfa_adjudicatorstampalldocsname";
			public const string DFA_Amended18MonthDeadline = "dfa_amended18monthdeadline";
			public const string DFA_AmendedProjectDeadlineDate = "dfa_amendedprojectdeadlinedate";
			public const string DFA_AmendmentApprovedDate = "dfa_amendmentapproveddate";
			public const string DFA_AmendmentDecision = "dfa_amendmentdecision";
			public const string DFA_AmendmentDecisionName = "dfa_amendmentdecisionname";
			public const string DFA_AmendmentNumber = "dfa_amendmentnumber";
			public const string DFA_AmendmentReason = "dfa_amendmentreason";
			public const string DFA_AmendmentReceivedDate = "dfa_amendmentreceiveddate";
			public const string DFA_AmendmentStages = "dfa_amendmentstages";
			public const string DFA_AmendmentStagesName = "dfa_amendmentstagesname";
			public const string DFA_AmendmentSubStages = "dfa_amendmentsubstages";
			public const string DFA_AmendmentSubStagesName = "dfa_amendmentsubstagesname";
			public const string DFA_ApprovalPendingAdditionalInfoRequested = "dfa_approvalpendingadditionalinforequested";
			public const string DFA_ApprovalPendingAdditionalInfoRequestedName = "dfa_approvalpendingadditionalinforequestedname";
			public const string DFA_ApprovalPendingInProgress = "dfa_approvalpendinginprogress";
			public const string DFA_ApprovalPendingInProgressName = "dfa_approvalpendinginprogressname";
			public const string DFA_ApprovedAdditionalProjectCost = "dfa_approvedadditionalprojectcost";
			public const string DFA_ApprovedAdditionalProjectCost_Base = "dfa_approvedadditionalprojectcost_base";
			public const string DFA_AssignedToAdjudicator = "dfa_assignedtoadjudicator";
			public const string DFA_AssignedToAdjudicatorName = "dfa_assignedtoadjudicatorname";
			public const string DFA_AssignedToEvaluator = "dfa_assignedtoevaluator";
			public const string DFA_AssignedToEvaluatorName = "dfa_assignedtoevaluatorname";
			public const string DFA_ComplianceCheck = "dfa_compliancecheck";
			public const string DFA_ComplianceCheckAdjustmentsForIGbLetter = "dfa_compliancecheckadjustmentsforigbletter";
			public const string DFA_ComplianceCheckAdjustmentsForIGbLetterName = "dfa_compliancecheckadjustmentsforigblettername";
			public const string DFA_ComplianceCheckBackupDocuments = "dfa_compliancecheckbackupdocuments";
			public const string DFA_ComplianceCheckBackupDocumentsName = "dfa_compliancecheckbackupdocumentsname";
			public const string DFA_ComplianceCheckCcAdditionalInfoRequested = "dfa_compliancecheckccadditionalinforequested";
			public const string DFA_ComplianceCheckCcAdditionalInfoRequestedName = "dfa_compliancecheckccadditionalinforequestedname";
			public const string DFA_ComplianceCheckEligibleProjectsCope = "dfa_compliancecheckeligibleprojectscope";
			public const string DFA_ComplianceCheckEligibleProjectsCopeName = "dfa_compliancecheckeligibleprojectscopename";
			public const string DFA_ComplianceCheckGenerateApprovalLetter = "dfa_compliancecheckgenerateapprovalletter";
			public const string DFA_ComplianceCheckGenerateApprovalLetterName = "dfa_compliancecheckgenerateapprovallettername";
			public const string DFA_ComplianceCheckName = "dfa_compliancecheckname";
			public const string DFA_ComplianceCheckPreexistingCondition = "dfa_compliancecheckpreexistingcondition";
			public const string DFA_ComplianceCheckPreexistingConditionName = "dfa_compliancecheckpreexistingconditionname";
			public const string DFA_ComplianceChecksTampaLlDocs = "dfa_compliancecheckstampalldocs";
			public const string DFA_ComplianceChecksTampaLlDocsName = "dfa_compliancecheckstampalldocsname";
			public const string DFA_DeadlineExtensionApproved = "dfa_deadlineextensionapproved";
			public const string DFA_DeadlineExtensionApprovedName = "dfa_deadlineextensionapprovedname";
			public const string DFA_DFA_Project_DFA_ProjectAmendment_Project = "dfa_dfa_project_dfa_projectamendment_Project";
			public const string DFA_EMCRApprovalComments = "dfa_emcrapprovalcomments";
			public const string DFA_EstimatedAdditionalProjectCost = "dfa_estimatedadditionalprojectcost";
			public const string DFA_EstimatedAdditionalProjectCost_Base = "dfa_estimatedadditionalprojectcost_base";
			public const string DFA_ExpenseAuthority = "dfa_expenseauthority";
			public const string DFA_ExpenseAuthorItYeaAdditionalInfoRequest = "dfa_expenseauthorityeaadditionalinforequest";
			public const string DFA_ExpenseAuthorItYeaAdditionalInfoRequestName = "dfa_expenseauthorityeaadditionalinforequestname";
			public const string DFA_ExpenseAuthorityName = "dfa_expenseauthorityname";
			public const string DFA_Name = "dfa_name";
			public const string DFA_Project = "dfa_project";
			public const string DFA_ProjectAmendmentId = "dfa_projectamendmentid";
			public const string Id = "dfa_projectamendmentid";
			public const string DFA_ProjectName = "dfa_projectname";
			public const string DFA_QualifiedReceiver = "dfa_qualifiedreceiver";
			public const string DFA_QualifiedReceiverName = "dfa_qualifiedreceivername";
			public const string DFA_QualifiedReceiverQRAdditionalInForEQueS = "dfa_qualifiedreceiverqradditionalinforeques";
			public const string DFA_QualifiedReceiverQRAdditionalInForEQueSName = "dfa_qualifiedreceiverqradditionalinforequesname";
			public const string DFA_RequestedAmendment18MonthDate = "dfa_requestedamendment18monthdate";
			public const string DFA_RequestForAdditionalProjectCost = "dfa_requestforadditionalprojectcost";
			public const string DFA_RequestForAdditionalProjectCostName = "dfa_requestforadditionalprojectcostname";
			public const string DFA_RequestForProjectDeadlineExtension = "dfa_requestforprojectdeadlineextension";
			public const string DFA_RequestForProjectDeadlineExtensionName = "dfa_requestforprojectdeadlineextensionname";
			public const string DFA_RequiresDecisionNote = "dfa_requiresdecisionnote";
			public const string DFA_RequiresDecisionNoteName = "dfa_requiresdecisionnotename";
			public const string DFA_StageAdjudicator = "dfa_stageadjudicator";
			public const string DFA_StageApprovedPending = "dfa_stageapprovedpending";
			public const string DFA_StageClosed = "dfa_stageclosed";
			public const string DFA_StageComplianceCheck = "dfa_stagecompliancecheck";
			public const string DFA_StageCreated = "dfa_stagecreated";
			public const string DFA_StageDecisionMade = "dfa_stagedecisionmade";
			public const string DFA_StageExpenseAuthority = "dfa_stageexpenseauthority";
			public const string DFA_StageQualifiedReceiver = "dfa_stagequalifiedreceiver";
			public const string DFA_StageUnderReview = "dfa_stageunderreview";
			public const string DFA_Submitted = "dfa_submitted";
			public const string DFA_SubmittedName = "dfa_submittedname";
			public const string DFA_UnderReviewAdditionalInfoRequested = "dfa_underreviewadditionalinforequested";
			public const string DFA_UnderReviewAdditionalInfoRequestedName = "dfa_underreviewadditionalinforequestedname";
			public const string DFA_UnderReviewInProgress = "dfa_underreviewinprogress";
			public const string DFA_UnderReviewInProgressName = "dfa_underreviewinprogressname";
			public const string DFA_WaitingOnPolicyLegal = "dfa_waitingonpolicylegal";
			public const string DFA_WaitingOnPolicyLegalName = "dfa_waitingonpolicylegalname";
			public const string ExchangerAte = "exchangerate";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string Lk_DFA_ProjectAmendment_CreatedBy = "lk_dfa_projectamendment_createdby";
			public const string Lk_DFA_ProjectAmendment_CreatedOnBehalfBy = "lk_dfa_projectamendment_createdonbehalfby";
			public const string Lk_DFA_ProjectAmendment_ModifiedBy = "lk_dfa_projectamendment_modifiedby";
			public const string Lk_DFA_ProjectAmendment_ModifiedOnBehalfBy = "lk_dfa_projectamendment_modifiedonbehalfby";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedByName = "modifiedbyname";
			public const string ModifiedByYomiName = "modifiedbyyominame";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
			public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwnerIdName = "owneridname";
			public const string OwnerIdYomiName = "owneridyominame";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string ProcessId = "processid";
			public const string ProcessStage_DFA_ProjectAmendment = "processstage_dfa_projectamendment";
			public const string StageId = "stageid";
			public const string StateCode = "statecode";
			public const string StateCodename = "statecodename";
			public const string StatusCode = "statuscode";
			public const string StatusCodename = "statuscodename";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string TransactionCurrencyId = "transactioncurrencyid";
			public const string TransactionCurrencyIdName = "transactioncurrencyidname";
			public const string TraversedPath = "traversedpath";
			public const string User_DFA_ProjectAmendment = "user_dfa_projectamendment";
			public const string UtcConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public DFA_ProjectAmendment(System.Guid id) : 
				base(EntityLogicalName, id)
		{
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public DFA_ProjectAmendment(string keyName, object keyValue) : 
				base(EntityLogicalName, keyName, keyValue)
		{
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public DFA_ProjectAmendment(Microsoft.Xrm.Sdk.KeyAttributeCollection keyAttributes) : 
				base(EntityLogicalName, keyAttributes)
		{
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public DFA_ProjectAmendment() : 
				base(EntityLogicalName)
		{
		}
		
		public const string PrimaryIdAttribute = "dfa_projectamendmentid";
		
		public const string PrimaryNameAttribute = "dfa_name";
		
		public const string EntitySchemaName = "dfa_projectamendment";
		
		public const string EntityLogicalName = "dfa_projectamendment";
		
		public const string EntityLogicalCollectionName = "dfa_projectamendments";
		
		public const string EntitySetName = "dfa_projectamendments";
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyname")]
		public string CreatedByName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyyominame")]
		public string CreatedByYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("createdonbehalfby", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyname")]
		public string CreatedOnBehalfByName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
		public string CreatedOnBehalfByYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_additionalprojectcostdecision")]
		public virtual DFA_ProjectAmendment_DFA_AdditionalProjectCostDecision? DFA_AdditionalProjectCostDecision
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((DFA_ProjectAmendment_DFA_AdditionalProjectCostDecision?)(EntityOptionSetEnum.GetEnum(this, "dfa_additionalprojectcostdecision")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_additionalprojectcostdecision", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_additionalprojectcostdecisionname")]
		public string DFA_AdditionalProjectCostDecisionName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_additionalprojectcostdecision"))
				{
					return this.FormattedValues["dfa_additionalprojectcostdecision"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_adjudication")]
		public System.Nullable<bool> DFA_Adjudication
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_adjudication");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_adjudication", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_adjudicationname")]
		public string DFA_AdjudicationName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_adjudication"))
				{
					return this.FormattedValues["dfa_adjudication"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_adjudicatoradditionalinforequested")]
		public System.Nullable<bool> DFA_AdjudicatorAdditionalInfoRequested
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_adjudicatoradditionalinforequested");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_adjudicatoradditionalinforequested", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_adjudicatoradditionalinforequestedname")]
		public string DFA_AdjudicatorAdditionalInfoRequestedName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_adjudicatoradditionalinforequested"))
				{
					return this.FormattedValues["dfa_adjudicatoradditionalinforequested"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_adjudicatoradjustmentsforigbletter")]
		public System.Nullable<bool> DFA_AdjudicatorAdjustmentsForIGbLetter
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_adjudicatoradjustmentsforigbletter");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_adjudicatoradjustmentsforigbletter", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_adjudicatoradjustmentsforigblettername")]
		public string DFA_AdjudicatorAdjustmentsForIGbLetterName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_adjudicatoradjustmentsforigbletter"))
				{
					return this.FormattedValues["dfa_adjudicatoradjustmentsforigbletter"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_adjudicatorbackupdocuments")]
		public System.Nullable<bool> DFA_AdjudicatorBackupDocuments
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_adjudicatorbackupdocuments");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_adjudicatorbackupdocuments", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_adjudicatorbackupdocumentsname")]
		public string DFA_AdjudicatorBackupDocumentsName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_adjudicatorbackupdocuments"))
				{
					return this.FormattedValues["dfa_adjudicatorbackupdocuments"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_adjudicatoreligibleprojectscope")]
		public System.Nullable<bool> DFA_AdjudicatorEligibleProjectsCope
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_adjudicatoreligibleprojectscope");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_adjudicatoreligibleprojectscope", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_adjudicatoreligibleprojectscopename")]
		public string DFA_AdjudicatorEligibleProjectsCopeName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_adjudicatoreligibleprojectscope"))
				{
					return this.FormattedValues["dfa_adjudicatoreligibleprojectscope"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_adjudicatorgenerateapprovalletter")]
		public System.Nullable<bool> DFA_AdjudicatorGenerateApprovalLetter
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_adjudicatorgenerateapprovalletter");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_adjudicatorgenerateapprovalletter", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_adjudicatorgenerateapprovallettername")]
		public string DFA_AdjudicatorGenerateApprovalLetterName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_adjudicatorgenerateapprovalletter"))
				{
					return this.FormattedValues["dfa_adjudicatorgenerateapprovalletter"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_adjudicatorpreexistingcondition")]
		public System.Nullable<bool> DFA_AdjudicatorPreexistingCondition
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_adjudicatorpreexistingcondition");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_adjudicatorpreexistingcondition", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_adjudicatorpreexistingconditionname")]
		public string DFA_AdjudicatorPreexistingConditionName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_adjudicatorpreexistingcondition"))
				{
					return this.FormattedValues["dfa_adjudicatorpreexistingcondition"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_adjudicatorstampalldocs")]
		public System.Nullable<bool> DFA_AdjudicatorsTampaLlDocs
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_adjudicatorstampalldocs");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_adjudicatorstampalldocs", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_adjudicatorstampalldocsname")]
		public string DFA_AdjudicatorsTampaLlDocsName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_adjudicatorstampalldocs"))
				{
					return this.FormattedValues["dfa_adjudicatorstampalldocs"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_amended18monthdeadline")]
		public System.Nullable<System.DateTime> DFA_Amended18MonthDeadline
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("dfa_amended18monthdeadline");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_amended18monthdeadline", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_amendedprojectdeadlinedate")]
		public System.Nullable<System.DateTime> DFA_AmendedProjectDeadlineDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("dfa_amendedprojectdeadlinedate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_amendedprojectdeadlinedate", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_amendmentapproveddate")]
		public System.Nullable<System.DateTime> DFA_AmendmentApprovedDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("dfa_amendmentapproveddate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_amendmentapproveddate", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_amendmentdecision")]
		public virtual DFA_ProjectDecision? DFA_AmendmentDecision
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((DFA_ProjectDecision?)(EntityOptionSetEnum.GetEnum(this, "dfa_amendmentdecision")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_amendmentdecision", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_amendmentdecisionname")]
		public string DFA_AmendmentDecisionName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_amendmentdecision"))
				{
					return this.FormattedValues["dfa_amendmentdecision"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_amendmentnumber")]
		public System.Nullable<int> DFA_AmendmentNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("dfa_amendmentnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_amendmentnumber", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_amendmentreason")]
		public string DFA_AmendmentReason
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("dfa_amendmentreason");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_amendmentreason", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_amendmentreceiveddate")]
		public System.Nullable<System.DateTime> DFA_AmendmentReceivedDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("dfa_amendmentreceiveddate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_amendmentreceiveddate", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_amendmentstages")]
		public virtual DFA_ProjectAmMen? DFA_AmendmentStages
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((DFA_ProjectAmMen?)(EntityOptionSetEnum.GetEnum(this, "dfa_amendmentstages")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_amendmentstages", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_amendmentstagesname")]
		public string DFA_AmendmentStagesName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_amendmentstages"))
				{
					return this.FormattedValues["dfa_amendmentstages"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_amendmentsubstages")]
		public virtual DFA_ProjectAmendmentSubStages? DFA_AmendmentSubStages
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((DFA_ProjectAmendmentSubStages?)(EntityOptionSetEnum.GetEnum(this, "dfa_amendmentsubstages")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_amendmentsubstages", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_amendmentsubstagesname")]
		public string DFA_AmendmentSubStagesName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_amendmentsubstages"))
				{
					return this.FormattedValues["dfa_amendmentsubstages"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_approvalpendingadditionalinforequested")]
		public System.Nullable<bool> DFA_ApprovalPendingAdditionalInfoRequested
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_approvalpendingadditionalinforequested");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_approvalpendingadditionalinforequested", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_approvalpendingadditionalinforequestedname")]
		public string DFA_ApprovalPendingAdditionalInfoRequestedName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_approvalpendingadditionalinforequested"))
				{
					return this.FormattedValues["dfa_approvalpendingadditionalinforequested"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_approvalpendinginprogress")]
		public System.Nullable<bool> DFA_ApprovalPendingInProgress
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_approvalpendinginprogress");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_approvalpendinginprogress", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_approvalpendinginprogressname")]
		public string DFA_ApprovalPendingInProgressName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_approvalpendinginprogress"))
				{
					return this.FormattedValues["dfa_approvalpendinginprogress"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_approvedadditionalprojectcost")]
		public Microsoft.Xrm.Sdk.Money DFA_ApprovedAdditionalProjectCost
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("dfa_approvedadditionalprojectcost");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_approvedadditionalprojectcost", value);
			}
		}
		
		/// <summary>
		/// Value of the Approved additional project cost in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_approvedadditionalprojectcost_base")]
		public Microsoft.Xrm.Sdk.Money DFA_ApprovedAdditionalProjectCost_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("dfa_approvedadditionalprojectcost_base");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_assignedtoadjudicator")]
		public System.Nullable<bool> DFA_AssignedToAdjudicator
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_assignedtoadjudicator");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_assignedtoadjudicator", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_assignedtoadjudicatorname")]
		public string DFA_AssignedToAdjudicatorName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_assignedtoadjudicator"))
				{
					return this.FormattedValues["dfa_assignedtoadjudicator"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_assignedtoevaluator")]
		public System.Nullable<bool> DFA_AssignedToEvaluator
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_assignedtoevaluator");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_assignedtoevaluator", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_assignedtoevaluatorname")]
		public string DFA_AssignedToEvaluatorName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_assignedtoevaluator"))
				{
					return this.FormattedValues["dfa_assignedtoevaluator"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_compliancecheck")]
		public System.Nullable<bool> DFA_ComplianceCheck
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_compliancecheck");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_compliancecheck", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_compliancecheckadjustmentsforigbletter")]
		public System.Nullable<bool> DFA_ComplianceCheckAdjustmentsForIGbLetter
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_compliancecheckadjustmentsforigbletter");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_compliancecheckadjustmentsforigbletter", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_compliancecheckadjustmentsforigblettername")]
		public string DFA_ComplianceCheckAdjustmentsForIGbLetterName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_compliancecheckadjustmentsforigbletter"))
				{
					return this.FormattedValues["dfa_compliancecheckadjustmentsforigbletter"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_compliancecheckbackupdocuments")]
		public System.Nullable<bool> DFA_ComplianceCheckBackupDocuments
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_compliancecheckbackupdocuments");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_compliancecheckbackupdocuments", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_compliancecheckbackupdocumentsname")]
		public string DFA_ComplianceCheckBackupDocumentsName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_compliancecheckbackupdocuments"))
				{
					return this.FormattedValues["dfa_compliancecheckbackupdocuments"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_compliancecheckccadditionalinforequested")]
		public System.Nullable<bool> DFA_ComplianceCheckCcAdditionalInfoRequested
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_compliancecheckccadditionalinforequested");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_compliancecheckccadditionalinforequested", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_compliancecheckccadditionalinforequestedname")]
		public string DFA_ComplianceCheckCcAdditionalInfoRequestedName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_compliancecheckccadditionalinforequested"))
				{
					return this.FormattedValues["dfa_compliancecheckccadditionalinforequested"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_compliancecheckeligibleprojectscope")]
		public System.Nullable<bool> DFA_ComplianceCheckEligibleProjectsCope
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_compliancecheckeligibleprojectscope");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_compliancecheckeligibleprojectscope", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_compliancecheckeligibleprojectscopename")]
		public string DFA_ComplianceCheckEligibleProjectsCopeName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_compliancecheckeligibleprojectscope"))
				{
					return this.FormattedValues["dfa_compliancecheckeligibleprojectscope"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_compliancecheckgenerateapprovalletter")]
		public System.Nullable<bool> DFA_ComplianceCheckGenerateApprovalLetter
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_compliancecheckgenerateapprovalletter");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_compliancecheckgenerateapprovalletter", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_compliancecheckgenerateapprovallettername")]
		public string DFA_ComplianceCheckGenerateApprovalLetterName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_compliancecheckgenerateapprovalletter"))
				{
					return this.FormattedValues["dfa_compliancecheckgenerateapprovalletter"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_compliancecheckname")]
		public string DFA_ComplianceCheckName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_compliancecheck"))
				{
					return this.FormattedValues["dfa_compliancecheck"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_compliancecheckpreexistingcondition")]
		public System.Nullable<bool> DFA_ComplianceCheckPreexistingCondition
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_compliancecheckpreexistingcondition");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_compliancecheckpreexistingcondition", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_compliancecheckpreexistingconditionname")]
		public string DFA_ComplianceCheckPreexistingConditionName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_compliancecheckpreexistingcondition"))
				{
					return this.FormattedValues["dfa_compliancecheckpreexistingcondition"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_compliancecheckstampalldocs")]
		public System.Nullable<bool> DFA_ComplianceChecksTampaLlDocs
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_compliancecheckstampalldocs");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_compliancecheckstampalldocs", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_compliancecheckstampalldocsname")]
		public string DFA_ComplianceChecksTampaLlDocsName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_compliancecheckstampalldocs"))
				{
					return this.FormattedValues["dfa_compliancecheckstampalldocs"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_deadlineextensionapproved")]
		public System.Nullable<bool> DFA_DeadlineExtensionApproved
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_deadlineextensionapproved");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_deadlineextensionapproved", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_deadlineextensionapprovedname")]
		public string DFA_DeadlineExtensionApprovedName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_deadlineextensionapproved"))
				{
					return this.FormattedValues["dfa_deadlineextensionapproved"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_emcrapprovalcomments")]
		public string DFA_EMCRApprovalComments
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("dfa_emcrapprovalcomments");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_emcrapprovalcomments", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_estimatedadditionalprojectcost")]
		public Microsoft.Xrm.Sdk.Money DFA_EstimatedAdditionalProjectCost
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("dfa_estimatedadditionalprojectcost");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_estimatedadditionalprojectcost", value);
			}
		}
		
		/// <summary>
		/// Value of the Estimated additional project cost in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_estimatedadditionalprojectcost_base")]
		public Microsoft.Xrm.Sdk.Money DFA_EstimatedAdditionalProjectCost_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("dfa_estimatedadditionalprojectcost_base");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_expenseauthority")]
		public System.Nullable<bool> DFA_ExpenseAuthority
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_expenseauthority");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_expenseauthority", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_expenseauthorityeaadditionalinforequest")]
		public System.Nullable<bool> DFA_ExpenseAuthorItYeaAdditionalInfoRequest
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_expenseauthorityeaadditionalinforequest");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_expenseauthorityeaadditionalinforequest", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_expenseauthorityeaadditionalinforequestname")]
		public string DFA_ExpenseAuthorItYeaAdditionalInfoRequestName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_expenseauthorityeaadditionalinforequest"))
				{
					return this.FormattedValues["dfa_expenseauthorityeaadditionalinforequest"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_expenseauthorityname")]
		public string DFA_ExpenseAuthorityName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_expenseauthority"))
				{
					return this.FormattedValues["dfa_expenseauthority"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// The name of the custom entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_name")]
		public string DFA_Name
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("dfa_name");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_name", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_project")]
		public Microsoft.Xrm.Sdk.EntityReference DFA_Project
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("dfa_project");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_project", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_projectamendmentid")]
		public System.Nullable<System.Guid> DFA_ProjectAmendmentId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("dfa_projectamendmentid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_projectamendmentid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_projectamendmentid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.DFA_ProjectAmendmentId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_projectname")]
		public string DFA_ProjectName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_project"))
				{
					return this.FormattedValues["dfa_project"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_qualifiedreceiver")]
		public System.Nullable<bool> DFA_QualifiedReceiver
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_qualifiedreceiver");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_qualifiedreceiver", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_qualifiedreceivername")]
		public string DFA_QualifiedReceiverName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_qualifiedreceiver"))
				{
					return this.FormattedValues["dfa_qualifiedreceiver"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_qualifiedreceiverqradditionalinforeques")]
		public System.Nullable<bool> DFA_QualifiedReceiverQRAdditionalInForEQueS
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_qualifiedreceiverqradditionalinforeques");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_qualifiedreceiverqradditionalinforeques", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_qualifiedreceiverqradditionalinforequesname")]
		public string DFA_QualifiedReceiverQRAdditionalInForEQueSName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_qualifiedreceiverqradditionalinforeques"))
				{
					return this.FormattedValues["dfa_qualifiedreceiverqradditionalinforeques"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_requestedamendment18monthdate")]
		public System.Nullable<System.DateTime> DFA_RequestedAmendment18MonthDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("dfa_requestedamendment18monthdate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_requestedamendment18monthdate", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_requestforadditionalprojectcost")]
		public System.Nullable<bool> DFA_RequestForAdditionalProjectCost
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_requestforadditionalprojectcost");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_requestforadditionalprojectcost", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_requestforadditionalprojectcostname")]
		public string DFA_RequestForAdditionalProjectCostName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_requestforadditionalprojectcost"))
				{
					return this.FormattedValues["dfa_requestforadditionalprojectcost"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_requestforprojectdeadlineextension")]
		public System.Nullable<bool> DFA_RequestForProjectDeadlineExtension
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_requestforprojectdeadlineextension");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_requestforprojectdeadlineextension", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_requestforprojectdeadlineextensionname")]
		public string DFA_RequestForProjectDeadlineExtensionName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_requestforprojectdeadlineextension"))
				{
					return this.FormattedValues["dfa_requestforprojectdeadlineextension"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_requiresdecisionnote")]
		public System.Nullable<bool> DFA_RequiresDecisionNote
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_requiresdecisionnote");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_requiresdecisionnote", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_requiresdecisionnotename")]
		public string DFA_RequiresDecisionNoteName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_requiresdecisionnote"))
				{
					return this.FormattedValues["dfa_requiresdecisionnote"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_stageadjudicator")]
		public System.Nullable<int> DFA_StageAdjudicator
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("dfa_stageadjudicator");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_stageadjudicator", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_stageapprovedpending")]
		public System.Nullable<int> DFA_StageApprovedPending
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("dfa_stageapprovedpending");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_stageapprovedpending", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_stageclosed")]
		public System.Nullable<int> DFA_StageClosed
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("dfa_stageclosed");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_stageclosed", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_stagecompliancecheck")]
		public System.Nullable<int> DFA_StageComplianceCheck
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("dfa_stagecompliancecheck");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_stagecompliancecheck", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_stagecreated")]
		public System.Nullable<int> DFA_StageCreated
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("dfa_stagecreated");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_stagecreated", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_stagedecisionmade")]
		public System.Nullable<int> DFA_StageDecisionMade
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("dfa_stagedecisionmade");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_stagedecisionmade", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_stageexpenseauthority")]
		public System.Nullable<int> DFA_StageExpenseAuthority
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("dfa_stageexpenseauthority");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_stageexpenseauthority", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_stagequalifiedreceiver")]
		public System.Nullable<int> DFA_StageQualifiedReceiver
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("dfa_stagequalifiedreceiver");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_stagequalifiedreceiver", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_stageunderreview")]
		public System.Nullable<int> DFA_StageUnderReview
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("dfa_stageunderreview");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_stageunderreview", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_submitted")]
		public System.Nullable<bool> DFA_Submitted
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_submitted");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_submitted", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_submittedname")]
		public string DFA_SubmittedName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_submitted"))
				{
					return this.FormattedValues["dfa_submitted"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_underreviewadditionalinforequested")]
		public System.Nullable<bool> DFA_UnderReviewAdditionalInfoRequested
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_underreviewadditionalinforequested");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_underreviewadditionalinforequested", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_underreviewadditionalinforequestedname")]
		public string DFA_UnderReviewAdditionalInfoRequestedName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_underreviewadditionalinforequested"))
				{
					return this.FormattedValues["dfa_underreviewadditionalinforequested"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_underreviewinprogress")]
		public System.Nullable<bool> DFA_UnderReviewInProgress
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_underreviewinprogress");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_underreviewinprogress", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_underreviewinprogressname")]
		public string DFA_UnderReviewInProgressName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_underreviewinprogress"))
				{
					return this.FormattedValues["dfa_underreviewinprogress"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_waitingonpolicylegal")]
		public System.Nullable<bool> DFA_WaitingOnPolicyLegal
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("dfa_waitingonpolicylegal");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("dfa_waitingonpolicylegal", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_waitingonpolicylegalname")]
		public string DFA_WaitingOnPolicyLegalName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("dfa_waitingonpolicylegal"))
				{
					return this.FormattedValues["dfa_waitingonpolicylegal"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Exchange rate for the currency associated with the entity with respect to the base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangerAte
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyname")]
		public string ModifiedByName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyyominame")]
		public string ModifiedByYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("modifiedonbehalfby", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
		public string ModifiedOnBehalfByName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
		public string ModifiedOnBehalfByYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		/// <summary>
		/// Name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridname")]
		public string OwnerIdName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Yomi name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridyominame")]
		public string OwnerIdYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Contains the id of the process associated with the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processid")]
		public System.Nullable<System.Guid> ProcessId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("processid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("processid", value);
			}
		}
		
		/// <summary>
		/// Contains the id of the stage where the entity is located.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("stageid")]
		public System.Nullable<System.Guid> StageId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("stageid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("stageid", value);
			}
		}
		
		/// <summary>
		/// Status of the Project Amendment
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual DFA_ProjectAmendment_StateCode? StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((DFA_ProjectAmendment_StateCode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecodename")]
		public string StateCodename
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("statecode"))
				{
					return this.FormattedValues["statecode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Reason for the status of the Project Amendment
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual DFA_ProjectAmendment_StatusCode? StatusCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((DFA_ProjectAmendment_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscodename")]
		public string StatusCodename
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("statuscode"))
				{
					return this.FormattedValues["statuscode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the currency associated with the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("transactioncurrencyid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyidname")]
		public string TransactionCurrencyIdName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("transactioncurrencyid"))
				{
					return this.FormattedValues["transactioncurrencyid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// A comma separated list of string values representing the unique identifiers of stages in a Business Process Flow Instance in the order that they occur.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("traversedpath")]
		public string TraversedPath
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("traversedpath");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("traversedpath", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UtcConversionTimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:1 dfa_dfa_project_dfa_projectamendment_Project
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dfa_project")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dfa_dfa_project_dfa_projectamendment_Project")]
		public EMBC.Database.Model.DFA_Project DFA_DFA_Project_DFA_ProjectAmendment_Project
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EMBC.Database.Model.DFA_Project>("dfa_dfa_project_dfa_projectamendment_Project", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<EMBC.Database.Model.DFA_Project>("dfa_dfa_project_dfa_projectamendment_Project", null, value);
			}
		}
		
		/// <summary>
		/// N:1 lk_dfa_projectamendment_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_dfa_projectamendment_createdby")]
		public EMBC.Database.Model.SystemUser Lk_DFA_ProjectAmendment_CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EMBC.Database.Model.SystemUser>("lk_dfa_projectamendment_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_dfa_projectamendment_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_dfa_projectamendment_createdonbehalfby")]
		public EMBC.Database.Model.SystemUser Lk_DFA_ProjectAmendment_CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EMBC.Database.Model.SystemUser>("lk_dfa_projectamendment_createdonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<EMBC.Database.Model.SystemUser>("lk_dfa_projectamendment_createdonbehalfby", null, value);
			}
		}
		
		/// <summary>
		/// N:1 lk_dfa_projectamendment_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_dfa_projectamendment_modifiedby")]
		public EMBC.Database.Model.SystemUser Lk_DFA_ProjectAmendment_ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EMBC.Database.Model.SystemUser>("lk_dfa_projectamendment_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_dfa_projectamendment_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_dfa_projectamendment_modifiedonbehalfby")]
		public EMBC.Database.Model.SystemUser Lk_DFA_ProjectAmendment_ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EMBC.Database.Model.SystemUser>("lk_dfa_projectamendment_modifiedonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<EMBC.Database.Model.SystemUser>("lk_dfa_projectamendment_modifiedonbehalfby", null, value);
			}
		}
		
		/// <summary>
		/// N:1 processstage_dfa_projectamendment
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("stageid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("processstage_dfa_projectamendment")]
		public EMBC.Database.Model.ProcessStage ProcessStage_DFA_ProjectAmendment
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EMBC.Database.Model.ProcessStage>("processstage_dfa_projectamendment", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<EMBC.Database.Model.ProcessStage>("processstage_dfa_projectamendment", null, value);
			}
		}
		
		/// <summary>
		/// N:1 user_dfa_projectamendment
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_dfa_projectamendment")]
		public EMBC.Database.Model.SystemUser User_DFA_ProjectAmendment
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<EMBC.Database.Model.SystemUser>("user_dfa_projectamendment", null);
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public DFA_ProjectAmendment(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (value != null && name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["dfa_projectamendmentid"] = base.Id;
                        break;
                    case "dfa_projectamendmentid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}
#pragma warning restore CS1591
