/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CurrentApplication } from '../../models/current-application';

export interface ApplicationGetApplicationDetailsForProject$Params {

/**
 * The application Id.
 */
  applicationId?: string;
}

export function applicationGetApplicationDetailsForProject(http: HttpClient, rootUrl: string, params?: ApplicationGetApplicationDetailsForProject$Params, context?: HttpContext): Observable<StrictHttpResponse<CurrentApplication>> {
  const rb = new RequestBuilder(rootUrl, applicationGetApplicationDetailsForProject.PATH, 'get');
  if (params) {
    rb.query('applicationId', params.applicationId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CurrentApplication>;
    })
  );
}

applicationGetApplicationDetailsForProject.PATH = '/api/applications/dfaapplicationbyID';
