/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DfaApplicationMain } from '../../models/dfa-application-main';

export interface ApplicationGetApplicationMain$Params {

/**
 * The application Id.
 */
  applicationId?: string;
}

export function applicationGetApplicationMain(http: HttpClient, rootUrl: string, params?: ApplicationGetApplicationMain$Params, context?: HttpContext): Observable<StrictHttpResponse<DfaApplicationMain>> {
  const rb = new RequestBuilder(rootUrl, applicationGetApplicationMain.PATH, 'get');
  if (params) {
    rb.query('applicationId', params.applicationId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DfaApplicationMain>;
    })
  );
}

applicationGetApplicationMain.PATH = '/api/applications/appmain/byId';
