/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApplicationContacts } from '../../models/application-contacts';

export interface ApplicationGetPrimaryContactByBCeId$Params {
  bceiduserguid?: string;
}

export function applicationGetPrimaryContactByBCeId(http: HttpClient, rootUrl: string, params?: ApplicationGetPrimaryContactByBCeId$Params, context?: HttpContext): Observable<StrictHttpResponse<ApplicationContacts>> {
  const rb = new RequestBuilder(rootUrl, applicationGetPrimaryContactByBCeId.PATH, 'get');
  if (params) {
    rb.query('bceiduserguid', params.bceiduserguid, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApplicationContacts>;
    })
  );
}

applicationGetPrimaryContactByBCeId.PATH = '/api/applications/getcontact/byId';
