/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApplicantSubtypeSubCategories } from '../../models/applicant-subtype-sub-categories';

export interface ApplicationGetApplicantSubSubTypes$Params {
}

export function applicationGetApplicantSubSubTypes(http: HttpClient, rootUrl: string, params?: ApplicationGetApplicantSubSubTypes$Params, context?: HttpContext): Observable<StrictHttpResponse<ApplicantSubtypeSubCategories>> {
  const rb = new RequestBuilder(rootUrl, applicationGetApplicantSubSubTypes.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApplicantSubtypeSubCategories>;
    })
  );
}

applicationGetApplicantSubSubTypes.PATH = '/api/applications/applicantsubsubtypes';
