/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApplicantSubtypes } from '../../models/applicant-subtypes';

export interface ApplicationGetApplicantSubTypes$Params {
}

export function applicationGetApplicantSubTypes(http: HttpClient, rootUrl: string, params?: ApplicationGetApplicantSubTypes$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ApplicantSubtypes>>> {
  const rb = new RequestBuilder(rootUrl, applicationGetApplicantSubTypes.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ApplicantSubtypes>>;
    })
  );
}

applicationGetApplicantSubTypes.PATH = '/api/applications/applicantsubtypes';
