/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AppealFileMetadataUpload } from '../../models/appeal-file-metadata-upload';

export interface AppealAttachmentGetAttachmentsByCaseId$Params {

/**
 * The case Id.
 */
  caseId?: string;
}

export function appealAttachmentGetAttachmentsByCaseId(http: HttpClient, rootUrl: string, params?: AppealAttachmentGetAttachmentsByCaseId$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<AppealFileMetadataUpload>>> {
  const rb = new RequestBuilder(rootUrl, appealAttachmentGetAttachmentsByCaseId.PATH, 'get');
  if (params) {
    rb.query('caseId', params.caseId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<AppealFileMetadataUpload>>;
    })
  );
}

appealAttachmentGetAttachmentsByCaseId.PATH = '/api/appeal/attachments/byCaseId';
