/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AppealFileUpload } from '../../models/appeal-file-upload';

export interface AppealAttachmentUpsertAttachment$Params {
  
    /**
     * The attachment data.
     */
    body: AppealFileUpload
}

export function appealAttachmentUpsertAttachment(http: HttpClient, rootUrl: string, params: AppealAttachmentUpsertAttachment$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, appealAttachmentUpsertAttachment.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<string>;
    })
  );
}

appealAttachmentUpsertAttachment.PATH = '/api/appeal/attachments';
