#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMBC.Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum DFA_RecoveryClaimType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Advanced Payment", 1, "#0000ff")]
		AdvancedPayment = 222710001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Standard Payment", 0, "#0000ff")]
		StandardPayment = 222710000,
	}
}
#pragma warning restore CS1591
