#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMBC.Database.Model
{
	
	
	/// <summary>
	/// Pay Group of the Supplier Site in CAS system.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum DFA_PayGroup
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("GEN CHQ", 0, "#0000ff")]
		GenChq = 222710000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("GEN EFT", 1, "#0000ff")]
		GenEft = 222710001,
	}
}
#pragma warning restore CS1591
