#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMBC.Database.Model
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum DFA_ProjectRole
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Adjudication", 0, "#0000ff")]
		Adjudication = 222710000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Compliance check", 1, "#0000ff")]
		ComplianceCheck = 222710001,
	}
}
#pragma warning restore CS1591
