/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Address } from '../models/address';
import { ProfileDataConflict } from '../models/profile-data-conflict';
export type AddressDataConflict = ProfileDataConflict & {
'dataElementName': string;
'conflictingValue'?: Address;
'originalValue'?: Address;
};
