/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FileCategoryAmendment } from '../models/file-category-amendment';

/**
 * Amendment Dynamics Metadata.
 */
export interface AmendmentFileMetadataUpload {
  amendmentId?: string;
  category?: FileCategoryAmendment;
  deleteFlag?: boolean | null;
  description?: string | null;
  fileName?: string;
  id?: string | null;
  mimeType?: string;
  projectId?: string;
  size?: number | null;
  uploadedDate?: string | null;
  url?: string;
}
