/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FileCategoryAmendment } from '../models/file-category-amendment';

/**
 * Amendment S3 File Upload.
 */
export interface AmendmentFileUpload {
  amendmentId?: string;
  category?: FileCategoryAmendment;
  deleteFlag?: boolean | null;
  description?: string | null;
  fileData?: string | null;
  fileName?: string | null;
  id?: string | null;
  mimeType?: string | null;
  projectId?: string;
  size?: number | null;
  uploadedDate?: string | null;
}
