/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApplicationStageOptionSet } from '../models/application-stage-option-set';

/**
 * Property Damage
 */
export interface ApplicationDetails {
  appStatus?: ApplicationStageOptionSet | null;
  applicantSubSubtype?: string | null;
  applicantSubtype?: string | null;
  damageFromDate?: string | null;
  damageToDate?: string | null;
  estimatedPercent?: string | null;
  eventId?: string | null;
  eventName?: string | null;
  floodDamage?: boolean | null;
  guidanceSupport?: boolean | null;
  landslideDamage?: boolean | null;
  legalName?: string | null;
  otherDamage?: boolean | null;
  otherDamageText?: string | null;
  stormDamage?: boolean | null;
  subtypeDFAComment?: string | null;
  subtypeOtherDetails?: string | null;
  wildfireDamage?: boolean | null;
}
