/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CommunityType } from '../models/community-type';
export interface AreaCommunity {
  areaCommunityId?: string;
  communityType?: CommunityType;
  name?: string;
}
