/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Authorized Representative
 */
export interface AuthorizedRepresentative {
  businessPhone?: string | null;
  email?: string | null;
  firstDeclaration?: boolean | null;
  firstName?: string | null;
  lastName?: string | null;
  positionTitle?: string | null;
  secondDeclaration?: boolean | null;
}
