/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum CommunityType {
  Undefined = 'Undefined',
  City = 'City',
  Town = 'Town',
  Village = 'Village',
  FirstNationsCommunity = 'FirstNationsCommunity',
  DistrictMunicipality = 'DistrictMunicipality',
  IndianGovernmentDistrict = 'IndianGovernmentDistrict',
  IndianReserve = 'IndianReserve',
  UrbanCommunity = 'UrbanCommunity',
  ResortMunicipality = 'ResortMunicipality',
  Community = 'Community'
}
