/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Code } from '../models/code';
import { CommunityType } from '../models/community-type';
export type CommunityCode = Code & {
'communityType'?: CommunityType;
'districtName'?: string;
};
