/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Contact {
  businessPhone?: string;
  cellPhone?: string;
  email?: string;
  firstName?: string;
  jobTitle?: string;
  lastName?: string;
  notes?: string;
}
