/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Invoice } from '../models/invoice';
export type CurrentInvoice = Invoice & {
'applicationId'?: string;
'projectId'?: string;
'claimId'?: string;
'invoiceId'?: string;
'status'?: string;
'statusLastUpdated'?: string;
'isErrorInStatus'?: boolean;
'isHidden'?: boolean;
'statusColor'?: string;
'claimDecision'?: string;
};
