/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CurrentProjectAppeal {
  appealReason?: string;
  appealStatus?: string;
  appealType?: string;
  id?: string;
}
