/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CurrentProjectAppeal {
  completedOn?: string | null;
  id?: string;
  name?: string;
  stage?: string;
  status?: string;
  submissionDate?: string | null;
}
