/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ClaimAmountAppeal } from '../models/claim-amount-appeal';
import { ClaimStatusBar } from '../models/claim-status-bar';
export interface CurrentClaim {
  advancedDrawdownAmount?: string;
  appealStatusBar?: Array<ClaimStatusBar>;
  applicationId?: string;
  approvedClaimTotal?: string;
  approvedReimbursePercent?: string;
  claimAppealDecision?: string;
  claimAppealNumber?: string;
  claimAppeals?: ClaimAmountAppeal;
  claimDecision?: string;
  claimId?: string;
  claimNumber?: string;
  claimPortalNote?: string;
  claimTotal?: string;
  claimType?: string | null;
  codingBlockSubmissionStatus?: string;
  createdDate?: string;
  dateFileClosed?: string;
  decisionDate?: string;
  eligiblePayable?: string;
  finalClaim?: boolean;
  firstClaim?: boolean;
  isAdjustmentClaim?: boolean | null;
  isErrorInStatus?: boolean;
  isHidden?: boolean;
  lessFirst1000?: string;
  paidClaimAmount?: string;
  paidClaimDate?: string;
  projectId?: string;
  stage?: string;
  status?: string;
  statusBar?: Array<ClaimStatusBar>;
  statusColor?: string;
  statusLastUpdated?: string;
  submittedDate?: string;
}
