/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RoomType } from '../models/room-type';

/**
 * Damaged Room
 */
export interface DamagedRoom {
  applicationId?: string;
  deleteFlag?: boolean;
  description?: string;
  id?: string | null;
  otherRoomType?: string | null;
  roomType?: RoomType;
}
