/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Invoice } from '../models/invoice';
export interface DfaInvoiceMain {
  claimId?: string | null;
  id?: string | null;
  invoice?: Invoice | null;
}
