/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AppTypeInsurance } from '../models/app-type-insurance';
import { Consent } from '../models/consent';
import { OtherPreScreeningQuestions } from '../models/other-pre-screening-questions';
import { ProfileVerification } from '../models/profile-verification';

/**
 * Application
 */
export interface DfaApplicationStart {
  appTypeInsurance?: AppTypeInsurance;
  consent?: Consent;
  id?: string | null;
  notifyUser?: boolean;
  otherPreScreeningQuestions?: OtherPreScreeningQuestions;
  profileVerification?: ProfileVerification;
}
