/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DisasterEvent {
  endDate?: string | null;
  eventId?: string | null;
  eventName?: string | null;
  id?: string | null;
  ninetyDayDeadline?: string | null;
  remainingDays?: string | null;
  startDate?: string | null;
}
