/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FeatureFlagConfiguration {
  useAdvancedPayments?: boolean;
  useAmendments?: boolean;
  useAppeals?: boolean;
  useAutoNotifications?: boolean;
}
