/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * File Category Options
 */
export enum FileCategory {
  PreEvent = 'Pre Event Condition',
  PostEvent = 'Post Event Condition',
  Reports = 'Reports',
  AdditionalDocuments = 'Additional Supporting Documents',
  ApplicationPDF = 'Application PDF'
}
