/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FileCategoryClaim } from '../models/file-category-claim';
import { RequiredDocumentTypeClaim } from '../models/required-document-type-claim';
export interface FileUploadClaim {
  claimId?: string | null;
  contentType?: string | null;
  deleteFlag?: boolean;
  fileData?: string | null;
  fileDescription?: string | null;
  fileName?: string | null;
  fileSize?: number | null;
  fileType?: FileCategoryClaim | null;
  fileTypeText?: string | null;
  id?: string | null;
  modifiedBy?: string | null;
  requiredDocumentType?: RequiredDocumentTypeClaim | null;
  uploadedDate?: string | null;
}
