/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FileCategoryAmendment } from '../models/file-category-amendment';
import { RequiredDocumentTypeAmendment } from '../models/required-document-type-amendment';
export interface FileUploadAmendment {
  contentType?: string | null;
  deleteFlag?: boolean;
  fileData?: string | null;
  fileDescription?: string | null;
  fileName?: string | null;
  fileSize?: number | null;
  fileType?: FileCategoryAmendment | null;
  fileTypeText?: string | null;
  id?: string | null;
  modifiedBy?: string | null;
  projectId?: string | null;
  requiredDocumentType?: RequiredDocumentTypeAmendment | null;
  uploadedDate?: string | null;
}
