/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Insurance Options
 */
export enum InsuranceOption {
  Yes = 'Yes, my insurance will cover all my losses.',
  Unsure = 'Yes, but I don\'t know if my insurance will cover all damages or for this event.',
  No = 'No'
}
