/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Invoice {
  actualInvoiceTotal?: string | null;
  eligibleGST?: string | null;
  emcrApprovedAmount?: string | null;
  emcrDecision?: string | null;
  emcrDecisionComments?: string | null;
  emcrDecisionDate?: string | null;
  goodsReceivedDate?: string | null;
  grossGST?: number | null;
  invoiceDate?: string | null;
  invoiceNumber?: string | null;
  isClaimforPartofTotalInvoice?: boolean | null;
  isGoodsReceivedonInvoiceDate?: boolean | null;
  netInvoiceBeingClaimed?: number | null;
  pst?: number | null;
  purposeOfGoodsServiceReceived?: string | null;
  reasonClaimingPartofTotalInvoice?: string | null;
  totalBeingClaimed?: string | null;
  vendorName?: string | null;
}
