/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InvoiceAppealModel {
  claimAppealId?: string;
  invoiceDecisionComments?: string;
  originInvoiceId?: string;
}
