/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Full Time Other Contact
 */
export interface OtherContact {
  applicationId?: string | null;
  cellPhone?: string | null;
  deleteFlag?: boolean;
  email?: string;
  firstName?: string;
  id?: string | null;
  jobTitle?: string | null;
  lastName?: string;
  otherNotes?: string | null;
  phoneNumber?: string;
}
