/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface OutageInformation {
  content?: string;
  outageEndDate?: string | null;
  outageStartDate?: string | null;
}
