/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export enum ProjectTypes {
  InfrastructureRepair = 'InfrastructureRepair',
  DebrisCleanup = 'DebrisCleanup',
  Engineering = 'Engineering',
  PlanningDesign = 'PlanningDesign',
  Other = 'Other'
}
