/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ClaimStageOptionSet } from '../models/claim-stage-option-set';
import { Invoice } from '../models/invoice';
export interface RecoveryClaim {
  advancedDrawdownAmount?: string | null;
  approvedClaimTotal?: string | null;
  approvedReimbursement?: string | null;
  claimDecision?: string | null;
  claimEligibleGST?: string | null;
  claimGrossGST?: string | null;
  claimNumber?: string | null;
  claimPST?: string | null;
  claimReceivedByEMCRDate?: string | null;
  claimStatus?: ClaimStageOptionSet | null;
  claimTotal?: string | null;
  decisionDate?: string | null;
  eligiblePayable?: string | null;
  invoices?: Array<Invoice> | null;
  isFirstClaimApproved?: boolean | null;
  isThisFinalClaim?: boolean | null;
  lessFirst1000?: string | null;
  paidClaimAmount?: string | null;
  paidClaimDate?: string | null;
  stage?: string | null;
  status?: string | null;
  totalActualClaim?: string | null;
  totalInvoicesBeingClaimed?: string | null;
}
