/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Room Types
 */
export enum RoomType {
  Bathroom = 'Bathroom',
  Bedroom = 'Bedroom',
  Dining = 'Dining room',
  Family = 'Family room',
  Garage = 'Garage',
  Kitchen = 'Kitchen',
  Laundry = 'Laundry room',
  Living = 'Living room',
  Other = 'Other'
}
