/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DfaAppealType } from '../models/dfa-appeal-type';
import { PrivateAppealDecision } from '../models/private-appeal-decision';
export interface AppealUpdateRequest {
  appealDecision?: PrivateAppealDecision | null;
  applicationId?: string | null;
  caseId: string;
  dateSigned?: string | null;
  id: string;
  reason: string;
  reviewedEvaluatorReport?: boolean | null;
  signature?: string | null;
  signedName?: string | null;
  status: string;
  type: DfaAppealType;
}
