/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FileCategory } from '../models/file-category';

/**
 * Appeal Dynamics Metadata
 */
export interface AppealFileMetadataUpload {
  appealId?: string;
  category?: FileCategory;
  deleteFlag?: boolean | null;
  description?: string | null;
  fileName?: string;
  id?: string | null;
  mimeType?: string;
  size?: number | null;
  uploadedDate?: string | null;
  url?: string;
}
