/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DfaAppealType } from '../models/dfa-appeal-type';
export interface AppealModel {
  caseId: string;
  dateSigned?: string | null;
  reason?: string | null;
  signature?: string | null;
  signedName?: string | null;
  status?: string | null;
  type?: DfaAppealType | null;
}
