/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DfaAppealType } from '../models/dfa-appeal-type';
import { SignAndSubmitModel } from '../models/sign-and-submit-model';
export interface AppealModel {
  applicationId?: string | null;
  caseId: string;
  reason: string;
  signAndSubmit?: SignAndSubmitModel;
  status: string;
  type: DfaAppealType;
}
