/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DfaAppealType } from '../models/dfa-appeal-type';
import { PrivateAppealDecision } from '../models/private-appeal-decision';
export interface AppealModel {
  appealDecision?: PrivateAppealDecision | null;
  caseId: string;
  dateSigned?: string | null;
  reason?: string | null;
  reviewedEvaluatorReport?: boolean | null;
  signature?: string | null;
  signedName?: string | null;
  status?: string | null;
  type?: DfaAppealType | null;
}
