/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Stage } from '../models/stage';
import { StateCode } from '../models/state-code';
export interface CasePaidAmountAppeal {
  activeStage?: Stage | null;
  caseAppealId?: string | null;
  id?: string;
  stages?: Array<Stage> | null;
  stateCode?: StateCode;
}
