/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Profile contact information
 */
export interface ContactDetails {
  alternatePhone?: string | null;
  cellPhoneNumber?: string | null;
  email?: string;
  residencePhone?: string | null;
}
