/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CurrentCaseAppeal } from '../models/current-case-appeal';
import { StatusBar } from '../models/status-bar';
export interface CurrentApplication {
  appeals?: Array<CurrentCaseAppeal>;
  applicationId?: string;
  applicationSubType?: string;
  applicationType?: string;
  caseNumber?: string;
  damagedAddress?: string;
  dateAppealClosed?: string;
  dateFileClosed?: string;
  dateOfDamage?: string;
  eventId?: string;
  hasAppealStages?: boolean;
  isErrorInStatus?: boolean;
  legalName?: string;
  primaryApplicantSignedDate?: string;
  status?: string;
  statusBar?: Array<StatusBar>;
  statusLastUpdated?: string;
}
