/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CaseEligibilityAppeal } from '../models/case-eligibility-appeal';
import { CasePaidAmountAppeal } from '../models/case-paid-amount-appeal';
import { StatusBar } from '../models/status-bar';
export interface CurrentApplication {
  amountAppealPortalNote?: string;
  amountAppealStatusPortal?: string;
  applicationId?: string;
  applicationSubType?: string;
  applicationType?: string;
  caseAmountAppeal?: CasePaidAmountAppeal;
  caseEligibility?: string;
  caseEligibilityAppeal?: CaseEligibilityAppeal;
  caseId?: string;
  caseNumber?: string;
  damagedAddress?: string;
  dateAppealClosed?: string;
  dateFileClosed?: string;
  dateOfDamage?: string;
  eventId?: string;
  hasAppealStages?: boolean;
  isErrorInStatus?: boolean;
  legalName?: string;
  primaryApplicantSignedDate?: string;
  status?: string;
  statusBar?: Array<StatusBar>;
  statusLastUpdated?: string;
}
