/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Farm Options
 */
export enum FarmOption {
  General = 'General Partnership, Sole Proprietorship, Unregistered, or DBA Name',
  Corporate = 'Corporate Company (Ltd./Inc.)'
}
