/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FileCategory } from '../models/file-category';
import { RequiredDocumentType } from '../models/required-document-type';

/**
 * File Upload
 */
export interface FileUpload {
  applicationId?: string;
  contentType?: string | null;
  deleteFlag?: boolean;
  fileData?: string | null;
  fileDescription?: string | null;
  fileName?: string | null;
  fileSize?: number | null;
  fileType?: FileCategory | null;
  id?: string | null;
  modifiedBy?: string | null;
  requiredDocumentType?: RequiredDocumentType | null;
  uploadedDate?: string | null;
}
