/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Full Time Occupants
 */
export interface FullTimeOccupant {
  applicationId?: string;
  deleteFlag?: boolean;
  firstName?: string;
  id?: string | null;
  lastName?: string;
  relationship?: string;
}
