/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Base class for profile data conflicts
 */
export interface ProfileDataConflict {
  dataElementName: string;
}
