/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SignatureBlockModel {
  dateSigned?: string;
  signature?: string;
  signedName?: string;
}
