/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SignatureBlock } from '../models/signature-block';
export interface SignAndSubmitModel {
  applicantSignature?: SignatureBlock;
  secondaryApplicantSignature?: SignatureBlock;
}
