/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Small Business Options
 */
export enum SmallBusinessOption {
  General = 'General or Sole Proprietorship or DBA name',
  Corporate = 'Corporate Company (Ltd./Inc.)',
  Landlord = 'Landlord'
}
