/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */


/**
 * Supporting Documents
 */
export interface SupportingDocuments {
  hasCopyOfARentalAgreementOrLease?: boolean | null;
}
