/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DfaProjectMain } from '../../models/dfa-project-main';

export interface ProjectGetProjectMain$Params {

/**
 * The project Id.
 */
  projectId?: string;
}

export function projectGetProjectMain(http: HttpClient, rootUrl: string, params?: ProjectGetProjectMain$Params, context?: HttpContext): Observable<StrictHttpResponse<DfaProjectMain>> {
  const rb = new RequestBuilder(rootUrl, projectGetProjectMain.PATH, 'get');
  if (params) {
    rb.query('projectId', params.projectId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DfaProjectMain>;
    })
  );
}

projectGetProjectMain.PATH = '/api/projects/appmain/byId';
