/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { attachmentDeleteProjectAttachment } from '../fn/attachment/attachment-delete-project-attachment';
import { AttachmentDeleteProjectAttachment$Params } from '../fn/attachment/attachment-delete-project-attachment';
import { attachmentGetClaimAttachments } from '../fn/attachment/attachment-get-claim-attachments';
import { AttachmentGetClaimAttachments$Params } from '../fn/attachment/attachment-get-claim-attachments';
import { attachmentGetProjectAttachments } from '../fn/attachment/attachment-get-project-attachments';
import { AttachmentGetProjectAttachments$Params } from '../fn/attachment/attachment-get-project-attachments';
import { attachmentUpsertDeleteClaimAttachment } from '../fn/attachment/attachment-upsert-delete-claim-attachment';
import { AttachmentUpsertDeleteClaimAttachment$Params } from '../fn/attachment/attachment-upsert-delete-claim-attachment';
import { attachmentUpsertDeleteProjectAttachment } from '../fn/attachment/attachment-upsert-delete-project-attachment';
import { AttachmentUpsertDeleteProjectAttachment$Params } from '../fn/attachment/attachment-upsert-delete-project-attachment';
import { FileUpload } from '../models/file-upload';
import { FileUploadClaim } from '../models/file-upload-claim';

@Injectable({ providedIn: 'root' })
export class AttachmentService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `attachmentDeleteProjectAttachment()` */
  static readonly AttachmentDeleteProjectAttachmentPath = '/api/attachments';

  /**
   * Create / update / delete a file attachment.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `attachmentDeleteProjectAttachment()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  attachmentDeleteProjectAttachment$Response(params: AttachmentDeleteProjectAttachment$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return attachmentDeleteProjectAttachment(this.http, this.rootUrl, params, context);
  }

  /**
   * Create / update / delete a file attachment.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `attachmentDeleteProjectAttachment$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  attachmentDeleteProjectAttachment(params: AttachmentDeleteProjectAttachment$Params, context?: HttpContext): Observable<string> {
    return this.attachmentDeleteProjectAttachment$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `attachmentUpsertDeleteProjectAttachment()` */
  static readonly AttachmentUpsertDeleteProjectAttachmentPath = '/api/attachments/projectdocument';

  /**
   * Create / update / delete a file attachment.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `attachmentUpsertDeleteProjectAttachment()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  attachmentUpsertDeleteProjectAttachment$Response(params: AttachmentUpsertDeleteProjectAttachment$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return attachmentUpsertDeleteProjectAttachment(this.http, this.rootUrl, params, context);
  }

  /**
   * Create / update / delete a file attachment.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `attachmentUpsertDeleteProjectAttachment$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  attachmentUpsertDeleteProjectAttachment(params: AttachmentUpsertDeleteProjectAttachment$Params, context?: HttpContext): Observable<string> {
    return this.attachmentUpsertDeleteProjectAttachment$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `attachmentUpsertDeleteClaimAttachment()` */
  static readonly AttachmentUpsertDeleteClaimAttachmentPath = '/api/attachments/claimdocument';

  /**
   * Create / update / delete a file attachment.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `attachmentUpsertDeleteClaimAttachment()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  attachmentUpsertDeleteClaimAttachment$Response(params: AttachmentUpsertDeleteClaimAttachment$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return attachmentUpsertDeleteClaimAttachment(this.http, this.rootUrl, params, context);
  }

  /**
   * Create / update / delete a file attachment.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `attachmentUpsertDeleteClaimAttachment$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  attachmentUpsertDeleteClaimAttachment(params: AttachmentUpsertDeleteClaimAttachment$Params, context?: HttpContext): Observable<string> {
    return this.attachmentUpsertDeleteClaimAttachment$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `attachmentGetProjectAttachments()` */
  static readonly AttachmentGetProjectAttachmentsPath = '/api/attachments/byProjectIdId';

  /**
   * Get a list of attachments by project Id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `attachmentGetProjectAttachments()` instead.
   *
   * This method doesn't expect any request body.
   */
  attachmentGetProjectAttachments$Response(params?: AttachmentGetProjectAttachments$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FileUpload>>> {
    return attachmentGetProjectAttachments(this.http, this.rootUrl, params, context);
  }

  /**
   * Get a list of attachments by project Id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `attachmentGetProjectAttachments$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  attachmentGetProjectAttachments(params?: AttachmentGetProjectAttachments$Params, context?: HttpContext): Observable<Array<FileUpload>> {
    return this.attachmentGetProjectAttachments$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<FileUpload>>): Array<FileUpload> => r.body)
    );
  }

  /** Path part for operation `attachmentGetClaimAttachments()` */
  static readonly AttachmentGetClaimAttachmentsPath = '/api/attachments/byclaimId';

  /**
   * Get a list of attachments by claim Id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `attachmentGetClaimAttachments()` instead.
   *
   * This method doesn't expect any request body.
   */
  attachmentGetClaimAttachments$Response(params?: AttachmentGetClaimAttachments$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FileUploadClaim>>> {
    return attachmentGetClaimAttachments(this.http, this.rootUrl, params, context);
  }

  /**
   * Get a list of attachments by claim Id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `attachmentGetClaimAttachments$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  attachmentGetClaimAttachments(params?: AttachmentGetClaimAttachments$Params, context?: HttpContext): Observable<Array<FileUploadClaim>> {
    return this.attachmentGetClaimAttachments$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<FileUploadClaim>>): Array<FileUploadClaim> => r.body)
    );
  }

}
