/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { attachmentDeleteProjectAppealAttachment } from '../fn/attachment/attachment-delete-project-appeal-attachment';
import { AttachmentDeleteProjectAppealAttachment$Params } from '../fn/attachment/attachment-delete-project-appeal-attachment';
import { attachmentDeleteProjectAttachment } from '../fn/attachment/attachment-delete-project-attachment';
import { AttachmentDeleteProjectAttachment$Params } from '../fn/attachment/attachment-delete-project-attachment';
import { attachmentGetAmendmentAttachments } from '../fn/attachment/attachment-get-amendment-attachments';
import { AttachmentGetAmendmentAttachments$Params } from '../fn/attachment/attachment-get-amendment-attachments';
import { attachmentGetClaimAppealAttachments } from '../fn/attachment/attachment-get-claim-appeal-attachments';
import { AttachmentGetClaimAppealAttachments$Params } from '../fn/attachment/attachment-get-claim-appeal-attachments';
import { attachmentGetClaimAttachments } from '../fn/attachment/attachment-get-claim-attachments';
import { AttachmentGetClaimAttachments$Params } from '../fn/attachment/attachment-get-claim-attachments';
import { attachmentGetProjectAppealAttachments } from '../fn/attachment/attachment-get-project-appeal-attachments';
import { AttachmentGetProjectAppealAttachments$Params } from '../fn/attachment/attachment-get-project-appeal-attachments';
import { attachmentGetProjectAttachments } from '../fn/attachment/attachment-get-project-attachments';
import { AttachmentGetProjectAttachments$Params } from '../fn/attachment/attachment-get-project-attachments';
import { attachmentUpsertDeleteClaimAppealAttachment } from '../fn/attachment/attachment-upsert-delete-claim-appeal-attachment';
import { AttachmentUpsertDeleteClaimAppealAttachment$Params } from '../fn/attachment/attachment-upsert-delete-claim-appeal-attachment';
import { attachmentUpsertDeleteClaimAttachment } from '../fn/attachment/attachment-upsert-delete-claim-attachment';
import { AttachmentUpsertDeleteClaimAttachment$Params } from '../fn/attachment/attachment-upsert-delete-claim-attachment';
import { attachmentUpsertDeleteProjectAmendmentAttachment } from '../fn/attachment/attachment-upsert-delete-project-amendment-attachment';
import { AttachmentUpsertDeleteProjectAmendmentAttachment$Params } from '../fn/attachment/attachment-upsert-delete-project-amendment-attachment';
import { attachmentUpsertDeleteProjectAttachment } from '../fn/attachment/attachment-upsert-delete-project-attachment';
import { AttachmentUpsertDeleteProjectAttachment$Params } from '../fn/attachment/attachment-upsert-delete-project-attachment';
import { attachmentUpsertProjectAppealAttachment } from '../fn/attachment/attachment-upsert-project-appeal-attachment';
import { AttachmentUpsertProjectAppealAttachment$Params } from '../fn/attachment/attachment-upsert-project-appeal-attachment';
import { FileUpload } from '../models/file-upload';
import { FileUploadAmendment } from '../models/file-upload-amendment';
import { FileUploadClaim } from '../models/file-upload-claim';
import { FileUploadClaimAppeal } from '../models/file-upload-claim-appeal';

@Injectable({ providedIn: 'root' })
export class AttachmentService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `attachmentDeleteProjectAttachment()` */
  static readonly AttachmentDeleteProjectAttachmentPath = '/api/attachments';

  /**
   * Create / update / delete a file attachment.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `attachmentDeleteProjectAttachment()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  attachmentDeleteProjectAttachment$Response(params: AttachmentDeleteProjectAttachment$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return attachmentDeleteProjectAttachment(this.http, this.rootUrl, params, context);
  }

  /**
   * Create / update / delete a file attachment.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `attachmentDeleteProjectAttachment$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  attachmentDeleteProjectAttachment(params: AttachmentDeleteProjectAttachment$Params, context?: HttpContext): Observable<string> {
    return this.attachmentDeleteProjectAttachment$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `attachmentUpsertDeleteProjectAttachment()` */
  static readonly AttachmentUpsertDeleteProjectAttachmentPath = '/api/attachments/projectdocument';

  /**
   * Create / update / delete a file attachment.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `attachmentUpsertDeleteProjectAttachment()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  attachmentUpsertDeleteProjectAttachment$Response(params: AttachmentUpsertDeleteProjectAttachment$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return attachmentUpsertDeleteProjectAttachment(this.http, this.rootUrl, params, context);
  }

  /**
   * Create / update / delete a file attachment.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `attachmentUpsertDeleteProjectAttachment$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  attachmentUpsertDeleteProjectAttachment(params: AttachmentUpsertDeleteProjectAttachment$Params, context?: HttpContext): Observable<string> {
    return this.attachmentUpsertDeleteProjectAttachment$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `attachmentUpsertDeleteProjectAmendmentAttachment()` */
  static readonly AttachmentUpsertDeleteProjectAmendmentAttachmentPath = '/api/attachments/amendmentdocument';

  /**
   * Create / update / delete a file attachment.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `attachmentUpsertDeleteProjectAmendmentAttachment()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  attachmentUpsertDeleteProjectAmendmentAttachment$Response(params: AttachmentUpsertDeleteProjectAmendmentAttachment$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return attachmentUpsertDeleteProjectAmendmentAttachment(this.http, this.rootUrl, params, context);
  }

  /**
   * Create / update / delete a file attachment.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `attachmentUpsertDeleteProjectAmendmentAttachment$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  attachmentUpsertDeleteProjectAmendmentAttachment(params: AttachmentUpsertDeleteProjectAmendmentAttachment$Params, context?: HttpContext): Observable<string> {
    return this.attachmentUpsertDeleteProjectAmendmentAttachment$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `attachmentUpsertDeleteClaimAttachment()` */
  static readonly AttachmentUpsertDeleteClaimAttachmentPath = '/api/attachments/claimdocument';

  /**
   * Create / update / delete a file attachment.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `attachmentUpsertDeleteClaimAttachment()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  attachmentUpsertDeleteClaimAttachment$Response(params: AttachmentUpsertDeleteClaimAttachment$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return attachmentUpsertDeleteClaimAttachment(this.http, this.rootUrl, params, context);
  }

  /**
   * Create / update / delete a file attachment.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `attachmentUpsertDeleteClaimAttachment$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  attachmentUpsertDeleteClaimAttachment(params: AttachmentUpsertDeleteClaimAttachment$Params, context?: HttpContext): Observable<string> {
    return this.attachmentUpsertDeleteClaimAttachment$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `attachmentUpsertProjectAppealAttachment()` */
  static readonly AttachmentUpsertProjectAppealAttachmentPath = '/api/attachments/projectAppealDocument';

  /**
   * Upsert (create or update) a project appeal attachment.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `attachmentUpsertProjectAppealAttachment()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  attachmentUpsertProjectAppealAttachment$Response(params: AttachmentUpsertProjectAppealAttachment$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return attachmentUpsertProjectAppealAttachment(this.http, this.rootUrl, params, context);
  }

  /**
   * Upsert (create or update) a project appeal attachment.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `attachmentUpsertProjectAppealAttachment$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  attachmentUpsertProjectAppealAttachment(params: AttachmentUpsertProjectAppealAttachment$Params, context?: HttpContext): Observable<string> {
    return this.attachmentUpsertProjectAppealAttachment$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `attachmentDeleteProjectAppealAttachment()` */
  static readonly AttachmentDeleteProjectAppealAttachmentPath = '/api/attachments/projectAppealDocument';

  /**
   * Delete a project appeal attachment.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `attachmentDeleteProjectAppealAttachment()` instead.
   *
   * This method doesn't expect any request body.
   */
  attachmentDeleteProjectAppealAttachment$Response(params?: AttachmentDeleteProjectAppealAttachment$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return attachmentDeleteProjectAppealAttachment(this.http, this.rootUrl, params, context);
  }

  /**
   * Delete a project appeal attachment.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `attachmentDeleteProjectAppealAttachment$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  attachmentDeleteProjectAppealAttachment(params?: AttachmentDeleteProjectAppealAttachment$Params, context?: HttpContext): Observable<string> {
    return this.attachmentDeleteProjectAppealAttachment$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `attachmentUpsertDeleteClaimAppealAttachment()` */
  static readonly AttachmentUpsertDeleteClaimAppealAttachmentPath = '/api/attachments/claimappealdocument';

  /**
   * Create / update / delete a file attachment.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `attachmentUpsertDeleteClaimAppealAttachment()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  attachmentUpsertDeleteClaimAppealAttachment$Response(params: AttachmentUpsertDeleteClaimAppealAttachment$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return attachmentUpsertDeleteClaimAppealAttachment(this.http, this.rootUrl, params, context);
  }

  /**
   * Create / update / delete a file attachment.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `attachmentUpsertDeleteClaimAppealAttachment$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  attachmentUpsertDeleteClaimAppealAttachment(params: AttachmentUpsertDeleteClaimAppealAttachment$Params, context?: HttpContext): Observable<string> {
    return this.attachmentUpsertDeleteClaimAppealAttachment$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `attachmentGetProjectAttachments()` */
  static readonly AttachmentGetProjectAttachmentsPath = '/api/attachments/byProjectIdId';

  /**
   * Get a list of attachments by project Id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `attachmentGetProjectAttachments()` instead.
   *
   * This method doesn't expect any request body.
   */
  attachmentGetProjectAttachments$Response(params?: AttachmentGetProjectAttachments$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FileUpload>>> {
    return attachmentGetProjectAttachments(this.http, this.rootUrl, params, context);
  }

  /**
   * Get a list of attachments by project Id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `attachmentGetProjectAttachments$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  attachmentGetProjectAttachments(params?: AttachmentGetProjectAttachments$Params, context?: HttpContext): Observable<Array<FileUpload>> {
    return this.attachmentGetProjectAttachments$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<FileUpload>>): Array<FileUpload> => r.body)
    );
  }

  /** Path part for operation `attachmentGetAmendmentAttachments()` */
  static readonly AttachmentGetAmendmentAttachmentsPath = '/api/attachments/byProjectId';

  /**
   * Get a list of amendment attachments by project Id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `attachmentGetAmendmentAttachments()` instead.
   *
   * This method doesn't expect any request body.
   */
  attachmentGetAmendmentAttachments$Response(params?: AttachmentGetAmendmentAttachments$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FileUploadAmendment>>> {
    return attachmentGetAmendmentAttachments(this.http, this.rootUrl, params, context);
  }

  /**
   * Get a list of amendment attachments by project Id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `attachmentGetAmendmentAttachments$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  attachmentGetAmendmentAttachments(params?: AttachmentGetAmendmentAttachments$Params, context?: HttpContext): Observable<Array<FileUploadAmendment>> {
    return this.attachmentGetAmendmentAttachments$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<FileUploadAmendment>>): Array<FileUploadAmendment> => r.body)
    );
  }

  /** Path part for operation `attachmentGetClaimAttachments()` */
  static readonly AttachmentGetClaimAttachmentsPath = '/api/attachments/byclaimId';

  /**
   * Get a list of attachments by claim Id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `attachmentGetClaimAttachments()` instead.
   *
   * This method doesn't expect any request body.
   */
  attachmentGetClaimAttachments$Response(params?: AttachmentGetClaimAttachments$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FileUploadClaim>>> {
    return attachmentGetClaimAttachments(this.http, this.rootUrl, params, context);
  }

  /**
   * Get a list of attachments by claim Id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `attachmentGetClaimAttachments$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  attachmentGetClaimAttachments(params?: AttachmentGetClaimAttachments$Params, context?: HttpContext): Observable<Array<FileUploadClaim>> {
    return this.attachmentGetClaimAttachments$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<FileUploadClaim>>): Array<FileUploadClaim> => r.body)
    );
  }

  /** Path part for operation `attachmentGetProjectAppealAttachments()` */
  static readonly AttachmentGetProjectAppealAttachmentsPath = '/api/attachments/byProjectAppealId';

  /**
   * Get a list of attachments by project appeal Id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `attachmentGetProjectAppealAttachments()` instead.
   *
   * This method doesn't expect any request body.
   */
  attachmentGetProjectAppealAttachments$Response(params?: AttachmentGetProjectAppealAttachments$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FileUpload>>> {
    return attachmentGetProjectAppealAttachments(this.http, this.rootUrl, params, context);
  }

  /**
   * Get a list of attachments by project appeal Id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `attachmentGetProjectAppealAttachments$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  attachmentGetProjectAppealAttachments(params?: AttachmentGetProjectAppealAttachments$Params, context?: HttpContext): Observable<Array<FileUpload>> {
    return this.attachmentGetProjectAppealAttachments$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<FileUpload>>): Array<FileUpload> => r.body)
    );
  }

  /** Path part for operation `attachmentGetClaimAppealAttachments()` */
  static readonly AttachmentGetClaimAppealAttachmentsPath = '/api/attachments/byClaimAppealId';

  /**
   * Get a list of attachments by claim appeal Id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `attachmentGetClaimAppealAttachments()` instead.
   *
   * This method doesn't expect any request body.
   */
  attachmentGetClaimAppealAttachments$Response(params?: AttachmentGetClaimAppealAttachments$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FileUploadClaimAppeal>>> {
    return attachmentGetClaimAppealAttachments(this.http, this.rootUrl, params, context);
  }

  /**
   * Get a list of attachments by claim appeal Id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `attachmentGetClaimAppealAttachments$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  attachmentGetClaimAppealAttachments(params?: AttachmentGetClaimAppealAttachments$Params, context?: HttpContext): Observable<Array<FileUploadClaimAppeal>> {
    return this.attachmentGetClaimAppealAttachments$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<FileUploadClaimAppeal>>): Array<FileUploadClaimAppeal> => r.body)
    );
  }

}
