/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { BCeIdBusiness } from '../models/b-ce-id-business';
import { BceidUserData } from '../models/bceid-user-data';
import { contactCreateAuditEvent } from '../fn/contact/contact-create-audit-event';
import { ContactCreateAuditEvent$Params } from '../fn/contact/contact-create-audit-event';
import { contactGetAuthenticatedStatus } from '../fn/contact/contact-get-authenticated-status';
import { ContactGetAuthenticatedStatus$Params } from '../fn/contact/contact-get-authenticated-status';
import { contactGetDashboardContactInfo } from '../fn/contact/contact-get-dashboard-contact-info';
import { ContactGetDashboardContactInfo$Params } from '../fn/contact/contact-get-dashboard-contact-info';
import { contactGetLoginInfo } from '../fn/contact/contact-get-login-info';
import { ContactGetLoginInfo$Params } from '../fn/contact/contact-get-login-info';

@Injectable({ providedIn: 'root' })
export class ContactService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `contactGetDashboardContactInfo()` */
  static readonly ContactGetDashboardContactInfoPath = '/api/contacts/dashboard';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `contactGetDashboardContactInfo()` instead.
   *
   * This method doesn't expect any request body.
   */
  contactGetDashboardContactInfo$Response(params?: ContactGetDashboardContactInfo$Params, context?: HttpContext): Observable<StrictHttpResponse<BCeIdBusiness>> {
    return contactGetDashboardContactInfo(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `contactGetDashboardContactInfo$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  contactGetDashboardContactInfo(params?: ContactGetDashboardContactInfo$Params, context?: HttpContext): Observable<BCeIdBusiness> {
    return this.contactGetDashboardContactInfo$Response(params, context).pipe(
      map((r: StrictHttpResponse<BCeIdBusiness>): BCeIdBusiness => r.body)
    );
  }

  /** Path part for operation `contactGetLoginInfo()` */
  static readonly ContactGetLoginInfoPath = '/api/contacts/getlogin';

  /**
   * If user isn't authenticated, return NULL.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `contactGetLoginInfo()` instead.
   *
   * This method doesn't expect any request body.
   */
  contactGetLoginInfo$Response(params?: ContactGetLoginInfo$Params, context?: HttpContext): Observable<StrictHttpResponse<BceidUserData>> {
    return contactGetLoginInfo(this.http, this.rootUrl, params, context);
  }

  /**
   * If user isn't authenticated, return NULL.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `contactGetLoginInfo$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  contactGetLoginInfo(params?: ContactGetLoginInfo$Params, context?: HttpContext): Observable<BceidUserData> {
    return this.contactGetLoginInfo$Response(params, context).pipe(
      map((r: StrictHttpResponse<BceidUserData>): BceidUserData => r.body)
    );
  }

  /** Path part for operation `contactGetAuthenticatedStatus()` */
  static readonly ContactGetAuthenticatedStatusPath = '/api/contacts/isauthenticated';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `contactGetAuthenticatedStatus()` instead.
   *
   * This method doesn't expect any request body.
   */
  contactGetAuthenticatedStatus$Response(params?: ContactGetAuthenticatedStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return contactGetAuthenticatedStatus(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `contactGetAuthenticatedStatus$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  contactGetAuthenticatedStatus(params?: ContactGetAuthenticatedStatus$Params, context?: HttpContext): Observable<boolean> {
    return this.contactGetAuthenticatedStatus$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

  /** Path part for operation `contactCreateAuditEvent()` */
  static readonly ContactCreateAuditEventPath = '/api/contacts/createaudit';

  /**
   * Gets the same BCeID user info as getlogin, but also ensures that a dfa_bceidusers record exists
   * for the current logged in user.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `contactCreateAuditEvent()` instead.
   *
   * This method doesn't expect any request body.
   */
  contactCreateAuditEvent$Response(params?: ContactCreateAuditEvent$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return contactCreateAuditEvent(this.http, this.rootUrl, params, context);
  }

  /**
   * Gets the same BCeID user info as getlogin, but also ensures that a dfa_bceidusers record exists
   * for the current logged in user.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `contactCreateAuditEvent$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  contactCreateAuditEvent(params?: ContactCreateAuditEvent$Params, context?: HttpContext): Observable<string> {
    return this.contactCreateAuditEvent$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

}
