/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { eventHasActiveEvent } from '../fn/event/event-has-active-event';
import { EventHasActiveEvent$Params } from '../fn/event/event-has-active-event';
import { HasActiveEventResponse } from '../models/has-active-event-response';

@Injectable({ providedIn: 'root' })
export class EventService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `eventHasActiveEvent()` */
  static readonly EventHasActiveEventPath = '/api/Event/hasactiveevent';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `eventHasActiveEvent()` instead.
   *
   * This method doesn't expect any request body.
   */
  eventHasActiveEvent$Response(params?: EventHasActiveEvent$Params, context?: HttpContext): Observable<StrictHttpResponse<HasActiveEventResponse>> {
    return eventHasActiveEvent(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `eventHasActiveEvent$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  eventHasActiveEvent(params?: EventHasActiveEvent$Params, context?: HttpContext): Observable<HasActiveEventResponse> {
    return this.eventHasActiveEvent$Response(params, context).pipe(
      map((r: StrictHttpResponse<HasActiveEventResponse>): HasActiveEventResponse => r.body)
    );
  }

}
