/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { ApplicationResult } from '../models/application-result';
import { filesDeleteFile } from '../fn/files/files-delete-file';
import { FilesDeleteFile$Params } from '../fn/files/files-delete-file';
import { filesDownloadFile } from '../fn/files/files-download-file';
import { FilesDownloadFile$Params } from '../fn/files/files-download-file';
import { filesReactivateFile } from '../fn/files/files-reactivate-file';
import { FilesReactivateFile$Params } from '../fn/files/files-reactivate-file';
import { filesUploadFile } from '../fn/files/files-upload-file';
import { FilesUploadFile$Params } from '../fn/files/files-upload-file';

@Injectable({ providedIn: 'root' })
export class FilesService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `filesDownloadFile()` */
  static readonly FilesDownloadFilePath = '/api/Files/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `filesDownloadFile()` instead.
   *
   * This method doesn't expect any request body.
   */
  filesDownloadFile$Response(params: FilesDownloadFile$Params, context?: HttpContext): Observable<StrictHttpResponse<Blob>> {
    return filesDownloadFile(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `filesDownloadFile$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  filesDownloadFile(params: FilesDownloadFile$Params, context?: HttpContext): Observable<Blob> {
    return this.filesDownloadFile$Response(params, context).pipe(
      map((r: StrictHttpResponse<Blob>): Blob => r.body)
    );
  }

  /** Path part for operation `filesUploadFile()` */
  static readonly FilesUploadFilePath = '/api/Files/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `filesUploadFile()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  filesUploadFile$Response(params: FilesUploadFile$Params, context?: HttpContext): Observable<StrictHttpResponse<ApplicationResult>> {
    return filesUploadFile(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `filesUploadFile$Response()` instead.
   *
   * This method sends `multipart/form-data` and handles request body of type `multipart/form-data`.
   */
  filesUploadFile(params: FilesUploadFile$Params, context?: HttpContext): Observable<ApplicationResult> {
    return this.filesUploadFile$Response(params, context).pipe(
      map((r: StrictHttpResponse<ApplicationResult>): ApplicationResult => r.body)
    );
  }

  /** Path part for operation `filesDeleteFile()` */
  static readonly FilesDeleteFilePath = '/api/Files/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `filesDeleteFile()` instead.
   *
   * This method doesn't expect any request body.
   */
  filesDeleteFile$Response(params: FilesDeleteFile$Params, context?: HttpContext): Observable<StrictHttpResponse<ApplicationResult>> {
    return filesDeleteFile(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `filesDeleteFile$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  filesDeleteFile(params: FilesDeleteFile$Params, context?: HttpContext): Observable<ApplicationResult> {
    return this.filesDeleteFile$Response(params, context).pipe(
      map((r: StrictHttpResponse<ApplicationResult>): ApplicationResult => r.body)
    );
  }

  /** Path part for operation `filesReactivateFile()` */
  static readonly FilesReactivateFilePath = '/api/Files/{id}/reactivate';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `filesReactivateFile()` instead.
   *
   * This method doesn't expect any request body.
   */
  filesReactivateFile$Response(params: FilesReactivateFile$Params, context?: HttpContext): Observable<StrictHttpResponse<ApplicationResult>> {
    return filesReactivateFile(this.http, this.rootUrl, params, context);
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `filesReactivateFile$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  filesReactivateFile(params: FilesReactivateFile$Params, context?: HttpContext): Observable<ApplicationResult> {
    return this.filesReactivateFile$Response(params, context).pipe(
      map((r: StrictHttpResponse<ApplicationResult>): ApplicationResult => r.body)
    );
  }

}
