/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { OtherContact } from '../models/other-contact';
import { otherContactGetOtherContacts } from '../fn/other-contact/other-contact-get-other-contacts';
import { OtherContactGetOtherContacts$Params } from '../fn/other-contact/other-contact-get-other-contacts';
import { otherContactUpsertDeleteOtherContact } from '../fn/other-contact/other-contact-upsert-delete-other-contact';
import { OtherContactUpsertDeleteOtherContact$Params } from '../fn/other-contact/other-contact-upsert-delete-other-contact';

@Injectable({ providedIn: 'root' })
export class OtherContactService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `otherContactUpsertDeleteOtherContact()` */
  static readonly OtherContactUpsertDeleteOtherContactPath = '/api/othercontacts';

  /**
   * Create / update / delete an other contact.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `otherContactUpsertDeleteOtherContact()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  otherContactUpsertDeleteOtherContact$Response(params: OtherContactUpsertDeleteOtherContact$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return otherContactUpsertDeleteOtherContact(this.http, this.rootUrl, params, context);
  }

  /**
   * Create / update / delete an other contact.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `otherContactUpsertDeleteOtherContact$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  otherContactUpsertDeleteOtherContact(params: OtherContactUpsertDeleteOtherContact$Params, context?: HttpContext): Observable<string> {
    return this.otherContactUpsertDeleteOtherContact$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `otherContactGetOtherContacts()` */
  static readonly OtherContactGetOtherContactsPath = '/api/othercontacts/byApplicationId';

  /**
   * Get a list of other contacts by application id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `otherContactGetOtherContacts()` instead.
   *
   * This method doesn't expect any request body.
   */
  otherContactGetOtherContacts$Response(params?: OtherContactGetOtherContacts$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<OtherContact>>> {
    return otherContactGetOtherContacts(this.http, this.rootUrl, params, context);
  }

  /**
   * Get a list of other contacts by application id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `otherContactGetOtherContacts$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  otherContactGetOtherContacts(params?: OtherContactGetOtherContacts$Params, context?: HttpContext): Observable<Array<OtherContact>> {
    return this.otherContactGetOtherContacts$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<OtherContact>>): Array<OtherContact> => r.body)
    );
  }

}
