/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CurrentProjectAmendment } from '../models/current-project-amendment';
import { projectAmendmentDeleteProjectAmendment } from '../fn/project-amendment/project-amendment-delete-project-amendment';
import { ProjectAmendmentDeleteProjectAmendment$Params } from '../fn/project-amendment/project-amendment-delete-project-amendment';
import { projectAmendmentGetDfaProjectAmendments } from '../fn/project-amendment/project-amendment-get-dfa-project-amendments';
import { ProjectAmendmentGetDfaProjectAmendments$Params } from '../fn/project-amendment/project-amendment-get-dfa-project-amendments';
import { projectAmendmentUpsertProjectAmendment } from '../fn/project-amendment/project-amendment-upsert-project-amendment';
import { ProjectAmendmentUpsertProjectAmendment$Params } from '../fn/project-amendment/project-amendment-upsert-project-amendment';

@Injectable({ providedIn: 'root' })
export class ProjectAmendmentService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `projectAmendmentGetDfaProjectAmendments()` */
  static readonly ProjectAmendmentGetDfaProjectAmendmentsPath = '/api/projectamendments/projectamendments';

  /**
   * get project amendments.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `projectAmendmentGetDfaProjectAmendments()` instead.
   *
   * This method doesn't expect any request body.
   */
  projectAmendmentGetDfaProjectAmendments$Response(params?: ProjectAmendmentGetDfaProjectAmendments$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CurrentProjectAmendment>>> {
    return projectAmendmentGetDfaProjectAmendments(this.http, this.rootUrl, params, context);
  }

  /**
   * get project amendments.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `projectAmendmentGetDfaProjectAmendments$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  projectAmendmentGetDfaProjectAmendments(params?: ProjectAmendmentGetDfaProjectAmendments$Params, context?: HttpContext): Observable<Array<CurrentProjectAmendment>> {
    return this.projectAmendmentGetDfaProjectAmendments$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<CurrentProjectAmendment>>): Array<CurrentProjectAmendment> => r.body)
    );
  }

  /** Path part for operation `projectAmendmentUpsertProjectAmendment()` */
  static readonly ProjectAmendmentUpsertProjectAmendmentPath = '/api/projectamendments/update';

  /**
   * create or update project amendment.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `projectAmendmentUpsertProjectAmendment()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  projectAmendmentUpsertProjectAmendment$Response(params: ProjectAmendmentUpsertProjectAmendment$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return projectAmendmentUpsertProjectAmendment(this.http, this.rootUrl, params, context);
  }

  /**
   * create or update project amendment.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `projectAmendmentUpsertProjectAmendment$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  projectAmendmentUpsertProjectAmendment(params: ProjectAmendmentUpsertProjectAmendment$Params, context?: HttpContext): Observable<string> {
    return this.projectAmendmentUpsertProjectAmendment$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `projectAmendmentDeleteProjectAmendment()` */
  static readonly ProjectAmendmentDeleteProjectAmendmentPath = '/api/projectamendments/{amendmentId}';

  /**
   * delete project amendment.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `projectAmendmentDeleteProjectAmendment()` instead.
   *
   * This method doesn't expect any request body.
   */
  projectAmendmentDeleteProjectAmendment$Response(params: ProjectAmendmentDeleteProjectAmendment$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
    return projectAmendmentDeleteProjectAmendment(this.http, this.rootUrl, params, context);
  }

  /**
   * delete project amendment.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `projectAmendmentDeleteProjectAmendment$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  projectAmendmentDeleteProjectAmendment(params: ProjectAmendmentDeleteProjectAmendment$Params, context?: HttpContext): Observable<boolean> {
    return this.projectAmendmentDeleteProjectAmendment$Response(params, context).pipe(
      map((r: StrictHttpResponse<boolean>): boolean => r.body)
    );
  }

}
