/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { CurrentProject } from '../models/current-project';
import { DfaProjectMain } from '../models/dfa-project-main';
import { projectGetDfaProjects } from '../fn/project/project-get-dfa-projects';
import { ProjectGetDfaProjects$Params } from '../fn/project/project-get-dfa-projects';
import { projectGetProjectDetailsForClaim } from '../fn/project/project-get-project-details-for-claim';
import { ProjectGetProjectDetailsForClaim$Params } from '../fn/project/project-get-project-details-for-claim';
import { projectGetProjectMain } from '../fn/project/project-get-project-main';
import { ProjectGetProjectMain$Params } from '../fn/project/project-get-project-main';
import { projectGetProjectTypes } from '../fn/project/project-get-project-types';
import { ProjectGetProjectTypes$Params } from '../fn/project/project-get-project-types';
import { ProjectTypes } from '../models/project-types';
import { projectUpsertProject } from '../fn/project/project-upsert-project';
import { ProjectUpsertProject$Params } from '../fn/project/project-upsert-project';

@Injectable({ providedIn: 'root' })
export class ProjectService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `projectGetDfaProjects()` */
  static readonly ProjectGetDfaProjectsPath = '/api/projects/dfaprojects';

  /**
   * get dfa applications.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `projectGetDfaProjects()` instead.
   *
   * This method doesn't expect any request body.
   */
  projectGetDfaProjects$Response(params?: ProjectGetDfaProjects$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<CurrentProject>>> {
    return projectGetDfaProjects(this.http, this.rootUrl, params, context);
  }

  /**
   * get dfa applications.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `projectGetDfaProjects$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  projectGetDfaProjects(params?: ProjectGetDfaProjects$Params, context?: HttpContext): Observable<Array<CurrentProject>> {
    return this.projectGetDfaProjects$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<CurrentProject>>): Array<CurrentProject> => r.body)
    );
  }

  /** Path part for operation `projectUpsertProject()` */
  static readonly ProjectUpsertProjectPath = '/api/projects/update';

  /**
   * create or update project.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `projectUpsertProject()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  projectUpsertProject$Response(params: ProjectUpsertProject$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
    return projectUpsertProject(this.http, this.rootUrl, params, context);
  }

  /**
   * create or update project.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `projectUpsertProject$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  projectUpsertProject(params: ProjectUpsertProject$Params, context?: HttpContext): Observable<string> {
    return this.projectUpsertProject$Response(params, context).pipe(
      map((r: StrictHttpResponse<string>): string => r.body)
    );
  }

  /** Path part for operation `projectGetProjectMain()` */
  static readonly ProjectGetProjectMainPath = '/api/projects/appmain/byId';

  /**
   * Get project main by Id.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `projectGetProjectMain()` instead.
   *
   * This method doesn't expect any request body.
   */
  projectGetProjectMain$Response(params?: ProjectGetProjectMain$Params, context?: HttpContext): Observable<StrictHttpResponse<DfaProjectMain>> {
    return projectGetProjectMain(this.http, this.rootUrl, params, context);
  }

  /**
   * Get project main by Id.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `projectGetProjectMain$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  projectGetProjectMain(params?: ProjectGetProjectMain$Params, context?: HttpContext): Observable<DfaProjectMain> {
    return this.projectGetProjectMain$Response(params, context).pipe(
      map((r: StrictHttpResponse<DfaProjectMain>): DfaProjectMain => r.body)
    );
  }

  /** Path part for operation `projectGetProjectDetailsForClaim()` */
  static readonly ProjectGetProjectDetailsForClaimPath = '/api/projects/dfaprojectbyID';

  /**
   * get dfa project details.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `projectGetProjectDetailsForClaim()` instead.
   *
   * This method doesn't expect any request body.
   */
  projectGetProjectDetailsForClaim$Response(params?: ProjectGetProjectDetailsForClaim$Params, context?: HttpContext): Observable<StrictHttpResponse<CurrentProject>> {
    return projectGetProjectDetailsForClaim(this.http, this.rootUrl, params, context);
  }

  /**
   * get dfa project details.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `projectGetProjectDetailsForClaim$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  projectGetProjectDetailsForClaim(params?: ProjectGetProjectDetailsForClaim$Params, context?: HttpContext): Observable<CurrentProject> {
    return this.projectGetProjectDetailsForClaim$Response(params, context).pipe(
      map((r: StrictHttpResponse<CurrentProject>): CurrentProject => r.body)
    );
  }

  /** Path part for operation `projectGetProjectTypes()` */
  static readonly ProjectGetProjectTypesPath = '/api/projects/projecttypes';

  /**
   * Get the applicant subtype records.
   *
   *
   *
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `projectGetProjectTypes()` instead.
   *
   * This method doesn't expect any request body.
   */
  projectGetProjectTypes$Response(params?: ProjectGetProjectTypes$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ProjectTypes>>> {
    return projectGetProjectTypes(this.http, this.rootUrl, params, context);
  }

  /**
   * Get the applicant subtype records.
   *
   *
   *
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `projectGetProjectTypes$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  projectGetProjectTypes(params?: ProjectGetProjectTypes$Params, context?: HttpContext): Observable<Array<ProjectTypes>> {
    return this.projectGetProjectTypes$Response(params, context).pipe(
      map((r: StrictHttpResponse<Array<ProjectTypes>>): Array<ProjectTypes> => r.body)
    );
  }

}
