/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CleanUpLogItem } from '../../models/clean-up-log-item';

export interface CleanUpLogItemUpsertDeleteCleanUpLogItem$Params {
  
    /**
     * The clean up log item information
     */
    body: CleanUpLogItem
}

export function cleanUpLogItemUpsertDeleteCleanUpLogItem(http: HttpClient, rootUrl: string, params: CleanUpLogItemUpsertDeleteCleanUpLogItem$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, cleanUpLogItemUpsertDeleteCleanUpLogItem.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<string>;
    })
  );
}

cleanUpLogItemUpsertDeleteCleanUpLogItem.PATH = '/api/cleanuplogitems';
