/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DfaProjectAmendmentMain } from '../../models/dfa-project-amendment-main';

export interface ProjectAmendmentUpsertProjectAmendment$Params {
  
    /**
     * The project amendment information
     */
    body: DfaProjectAmendmentMain
}

export function projectAmendmentUpsertProjectAmendment(http: HttpClient, rootUrl: string, params: ProjectAmendmentUpsertProjectAmendment$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, projectAmendmentUpsertProjectAmendment.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<string>;
    })
  );
}

projectAmendmentUpsertProjectAmendment.PATH = '/api/projectamendments/update';
