/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DfaClaimMain } from '../../models/dfa-claim-main';

export interface ClaimGetClaimMain$Params {

/**
 * The claim Id.
 */
  claimId?: string;
}

export function claimGetClaimMain(http: HttpClient, rootUrl: string, params?: ClaimGetClaimMain$Params, context?: HttpContext): Observable<StrictHttpResponse<DfaClaimMain>> {
  const rb = new RequestBuilder(rootUrl, claimGetClaimMain.PATH, 'get');
  if (params) {
    rb.query('claimId', params.claimId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DfaClaimMain>;
    })
  );
}

claimGetClaimMain.PATH = '/api/claims/appmain/byClaimId';
