name: Build Private Portal UI

on:
  push:
    branches:
      - support-develop

    paths:
      - "dfa/src/UI/**"
      - ".github/workflows/cd-private-portal-ui.yaml"

env:
  IMAGE_NAME: dfa-portal-ui
  DFA_PRIVATE_UI_DOCKERFILE_PATH: ./dfa/src/UI/Dockerfile
  IMAGE_REGISTRY: ${{ secrets.OCP4_REGISTRY }}/${{ secrets.OCP4_NAMESPACE }}

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx tooling
        uses: docker/setup-buildx-action@v3

      - name: Log into OpenShift Registry
        uses: docker/login-action@v3
        with:
            registry: ${{ env.IMAGE_REGISTRY }}
            username: ${{ secrets.OCP4_USERNAME }}
            password: ${{ secrets.OCP4_PASSWORD }}
      
      - name: Pull image
        run: docker pull ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:latest || true

      - name: Bump version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ${{ env.IMAGE_NAME }}=v
          fetch_all_tags: true
      
      - name: Create version environment variable
        run: echo "VERSION=$(echo '${{ steps.tag_version.outputs.new_tag }}' | awk -F-v '{print $NF}')" >> $GITHUB_ENV

      - name: Build and push dfa-portal-ui
        uses: docker/build-push-action@v6
        with:
          build-args: |
            VERSION=${{ env.VERSION }}
          cache-from: |
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
          file: ${{ env.DFA_PRIVATE_UI_DOCKERFILE_PATH }}
          push: true
          tags: |
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}:latest
