#CD pipeline for dfa test branch private

name: test-project-private-build-push.yml

on:
  push:
    branches:
       - project-test

    paths:
      - "dfa/src/**"
      - ".github/workflows/test-project-private-build-push.yml"
  workflow_dispatch:

concurrency:
  group: test-build
  cancel-in-progress: false

env:
  UI_IMAGE_NAME: dfa-portal-ui
  API_IMAGE_NAME: dfa-portal-api
  AUTH_IMAGE_NAME: oauth-server
  UI_WORKING_DIRECTORY: ./dfa/src/UI
  API_WORKING_DIRECTORY: ./dfa/src/API
  AUTH_WORKING_DIRECTORY: ./oauth-server/src/API
  IMAGE_TAG: test

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v3

      - name: Log into registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_PROJECT_REGISTRY }}
          username: ${{ secrets.DOCKER_PROJECT_USERNAME }}
          password: ${{ secrets.DOCKER_PROJECT_PASSWORD_BUILDER }}

      # Get SHORT_SHA to tag images
      - name: Get short SHA
        id: short_sha
        run: |
          echo "::set-output name=SHORT_SHA::$(git rev-parse --short HEAD)"
          echo "Short SHA: $SHORT_SHA"

      - name: Build UI Image
        working-directory: ${{env.UI_WORKING_DIRECTORY}}
        run: |
          docker build -t ${{env.UI_IMAGE_NAME}} .

      - name: Tag UI Image
        run: |
          docker tag ${{env.UI_IMAGE_NAME}} ${{ secrets.DOCKER_PROJECT_REGISTRY }}/${{env.UI_IMAGE_NAME}}:${{ env.IMAGE_TAG }}

      - name: Docker UI Push
        run: |
          docker push ${{ secrets.DOCKER_PROJECT_REGISTRY }}/${{env.UI_IMAGE_NAME}}:${{ env.IMAGE_TAG }}

      - name: Build API Image
        working-directory: ${{env.API_WORKING_DIRECTORY}}
        run: |
          docker build -t ${{env.API_IMAGE_NAME}} .

      - name: Tag API Image
        run: |
          docker tag ${{env.API_IMAGE_NAME}} ${{ secrets.DOCKER_PROJECT_REGISTRY }}/${{env.API_IMAGE_NAME}}:${{ env.IMAGE_TAG }}

      - name: Docker API Push
        run: |
          docker push ${{ secrets.DOCKER_PROJECT_REGISTRY }}/${{env.API_IMAGE_NAME}}:${{ env.IMAGE_TAG }}

      
      - name: Build AUTH Image
        working-directory: ${{env.AUTH_WORKING_DIRECTORY}}
        run: |
          docker build -t ${{env.AUTH_IMAGE_NAME}} .

      - name: Tag AUTH Image
        run: |
          docker tag ${{env.AUTH_IMAGE_NAME}} ${{ secrets.DOCKER_PROJECT_REGISTRY }}/${{env.AUTH_IMAGE_NAME}}:${{ env.IMAGE_TAG }}

      - name: Docker AUTH Push
        run: |
          docker push ${{ secrets.DOCKER_PROJECT_REGISTRY }}/${{env.AUTH_IMAGE_NAME}}:${{ env.IMAGE_TAG }}
      
     
      - name: Checkout ArgoCD Repo
        id: gitops
        uses: actions/checkout@v4
        with:
          repository: bcgov-c/tenant-gitops-c2ee1a
          ref: test
          token: ${{ secrets.GITOPS_KEY }} # `GH_PAT` is a secret that contains your PAT
          path: gitops

      - name: Update Helm values in gitops
        id: helm
        if: steps.gitops.outcome == 'success'  # Only run if the previous step (publish) was successful
        run: |
          # Clone the GitOps deployment configuration repository
          # Navigate to the directory containing your Helm values file for the environment develop -> DEV, test -> test and 
          cd gitops/charts
          
          # Update the Helm values file with the new image tag and version
          DATETIME=$(date +'%Y-%m-%d %H:%M:%S')  # Get current date and time
          
          sed -i  "s/apitag: .*/apitag: test # Image Updated on $DATETIME/" ../deploy/test_values.yaml
          sed -i  "s/apiversion: .*/apiversion: v-${{ steps.short_sha.outputs.SHORT_SHA }} # Version Updated on $DATETIME/" ../deploy/test_values.yaml

          sed -i  "s/uitag: .*/uitag: test # Image Updated on $DATETIME/" ../deploy/test_values.yaml
          sed -i  "s/uiversion: .*/uiversion: v-${{ steps.short_sha.outputs.SHORT_SHA }} # Version Updated on $DATETIME/" ../deploy/test_values.yaml

          sed -i  "s/authtag: .*/authtag: test # Image Updated on $DATETIME/" ../deploy/test_values.yaml
          sed -i  "s/authversion: .*/authversion: v-${{ steps.short_sha.outputs.SHORT_SHA }} # Version Updated on $DATETIME/" ../deploy/test_values.yaml

          # Commit and push the changes
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      
          git add ../deploy/test_values.yaml

          # Repackage Helm Chart

          cd dfa-gitops

          helm dependency build

          cd charts

          git add .

          git commit -m "Update Test Private API and UI image tag"
          git push origin test  # Update the branch name as needed